// Datengrundlage V2: identisch zu V1 (Magier/Erzfeinde/Schaetze), ergaenzt um marketplaceCards
// (extrahiert aus github.com/on3iro/aeons-end-randomizer, deutsche Datensaetze, 179 Marktplatzkarten).
const AEONS_DATA = {
  "expansions": {
    "AE": {
      "code": "AE",
      "name": "Aeons End",
      "category": "base",
      "wave": 1
    },
    "Depths": {
      "code": "Depths",
      "name": "Aus den Tiefen",
      "category": "mini",
      "wave": 1
    },
    "Nameless": {
      "code": "Nameless",
      "name": "Das Namenlose",
      "category": "mini",
      "wave": 1
    },
    "WE": {
      "code": "WE",
      "name": "Für die Ewigkeit",
      "category": "base",
      "wave": 2
    },
    "OD": {
      "code": "OD",
      "name": "Hinter der Finsternis",
      "category": "mini",
      "wave": 2
    },
    "TV": {
      "code": "TV",
      "name": "Die Leere",
      "category": "mini",
      "wave": 2
    },
    "Legacy": {
      "code": "Legacy",
      "name": "Legacy",
      "category": "base",
      "wave": 3
    },
    "LegacyDangerousKnowledge": {
      "code": "LegacyDangerousKnowledge",
      "name": "Gefährliches Wissen",
      "category": "mini",
      "wave": 3
    },
    "NA": {
      "code": "NA",
      "name": "Ein neues Zeitalter",
      "category": "base",
      "wave": 4
    },
    "TA": {
      "code": "TA",
      "name": "Die Zeitlosen",
      "category": "mini",
      "wave": 4
    },
    "IW": {
      "code": "IW",
      "name": "In die Wildnis",
      "category": "mini",
      "wave": 4
    },
    "SD": {
      "code": "SD",
      "name": "Zerschmetterte Hoffnung",
      "category": "mini",
      "wave": 4
    },
    "promos": {
      "code": "promos",
      "name": "Promos",
      "category": "mini",
      "wave": 0
    }
  },
  "mages": [
    {
      "id": "Adelheim",
      "tier": "A",
      "name": "Adelheim",
      "expansion": "AE",
      "title": "Riss-Magier-Waffenschmied",
      "abilityName": "Aetherium Schutzwall",
      "abilityEffect": "Im Erzfeind-Zug während der Erzfeind-Aktion: Zieht ihr einen ANGRIFF oder PLAN? Wirf ihn ab. Er wird nicht ausgeführt und ihr zieht keinen Ersatz.",
      "charges": 5
    },
    {
      "id": "Brama",
      "tier": "D",
      "name": "Brama",
      "expansion": "AE",
      "title": "Riss-Magier-Älteste",
      "abilityName": "Den Abgrund Abschöpfen",
      "abilityEffect": "In Deinem Spieler-Zug während Aktionen ausführen: Wähle 1 Spieler, der 4 Leben heilt.",
      "charges": 5
    },
    {
      "id": "Jian",
      "tier": "B",
      "name": "Jian",
      "expansion": "AE",
      "title": "Riss-Magier-Waise",
      "abilityName": "Schwarzer Spiegel",
      "abilityEffect": "In Deinem Spieler-Zug während Aktionen ausführen: Wähle 1 Spieler und wirke 1 seiner gebundenen Zauber. Der Zauber bleibt gebunden. Dann wirke diesen Zauber erneut (und er wird abgelegt, wie üblich).",
      "charges": 4
    },
    {
      "id": "Kadir",
      "tier": "B",
      "name": "Kadir",
      "expansion": "AE",
      "title": "Riss-Magier-Forscherin",
      "abilityName": "Tor ins Anderseits",
      "abilityEffect": "Im Spieler-Zug Deiner Wahl während Aktionen ausführen: Der Spieler darf bis zu 3 Zauber aus seinem Ablagestapel zurück auf die Hand nehmen. Dann darf er bis zu 2 Zauber an jeden seiner aktiven Risse binden.",
      "charges": 5,
      "gender": "w"
    },
    {
      "id": "Lash",
      "tier": "A",
      "name": "Lash",
      "expansion": "AE",
      "title": "Riss-Magier-Späher",
      "abilityName": "Blitzschnell Reagieren",
      "abilityEffect": "Im Spieler-Zug Deiner Wahl während Aktionen ausführen: Mische die Spieler-Reihenfolgekarte 1 Spielers deiner Wahl zurück in das Reihenfolgedeck und füge diesem Spieler 1 Schaden zu.",
      "charges": 5
    },
    {
      "id": "Mist",
      "tier": "C",
      "name": "Mist",
      "expansion": "AE",
      "title": "Kapitänin der Dolchspitze",
      "abilityName": "Rat der Zukunft",
      "abilityEffect": "In Deinem Spieler-Zug während Aktionen ausführen: Wähle 1 anderen Spieler, der 4 Karten zieht.",
      "charges": 5,
      "gender": "w"
    },
    {
      "id": "Phaedraxa",
      "tier": "B",
      "name": "Phaedraxa",
      "expansion": "AE",
      "title": "Riss-Magier-Seherin",
      "abilityName": "Rune der Vorsicht",
      "abilityEffect": "Direkt nachdem ihr eine Reihenfolgekarte Gezogen habt: Verhindere in diesem Zug allen Schaden, der den Spielern wie auch der Feste der letzten Ruhe zugefügt wird.",
      "charges": 5,
      "gender": "w"
    },
    {
      "id": "Xaxos",
      "tier": "C",
      "name": "Xaxos",
      "expansion": "AE",
      "title": "Riss-Magier-Adept",
      "abilityName": "Metaphysische Verbindung",
      "abilityEffect": "Im Spieler-Zug Deiner Wahl während Aktionen ausführen: Erhalte insgesamt 4 Energie und verteile sie auf andere Spieler deiner Wahl. Decke alle noch verdeckten Reihenfolgekarten auf und lege sie in einer Reihenfolge deiner Wahl verdeckt zurück.",
      "charges": 5
    },
    {
      "id": "Inco",
      "tier": "C",
      "name": "Inco",
      "expansion": "IW",
      "title": "Kind der Natur",
      "abilityName": "Wucherndes Wachstum",
      "abilityEffect": "In deinem Spieler-Zug während Aktionen ausführen: Wirke beliebig viele gebundene Rosendornen (bei 1 oder mehr Spielern) mit jeweils +2 Schaden.",
      "charges": 5
    },
    {
      "id": "Razra",
      "tier": "A",
      "name": "Razra",
      "expansion": "IW",
      "title": "Riss-Magier-Bändigerin",
      "abilityName": "Reißer abrichten",
      "abilityEffect": "In deinem Spieler-Zug während Aktionen ausführen: Zerstöre 1 Reißer-Karte auf deiner Hand. Erwirb gratis 1 Reißer-Karte von deinem Reißer-Stapel, die bis zu 3 Æ mehr kostet. Nimm sie direkt auf die Hand. ODER Nimm alle Reißer-Karten aus deinem Ablagestapel zurück auf die Hand.",
      "charges": 4,
      "gender": "w"
    },
    {
      "id": "LegacyGreen",
      "tier": "S",
      "name": "Elariel",
      "expansion": "Legacy",
      "title": "Runenschützin",
      "abilityName": "Custom",
      "abilityEffect": "In deinem Schritt Aktionen ausführen: Wähle 1 Spieler, der 3 Leben heilt. UND Wähle 1 anderen Spieler, der 2 Energie erhält.",
      "charges": "Custom"
    },
    {
      "id": "LegacyYellow",
      "tier": "S",
      "name": "Radhan",
      "expansion": "Legacy",
      "title": "Riss-Springer",
      "abilityName": "Custom",
      "abilityEffect": "In deinem Schritt Aktionen ausführen: Erwirb gratis 1 Zauber deiner Wahl. Du darfst 1 anderen Spieler wählen, der ihn auf die Hand nimmt. UND Wähle 1 Spieler. Dieser Spieler darf 1 Zauber seiner Wahl aus seinem Ablagestapel zurück auf die Hand nehmen.",
      "charges": "Custom"
    },
    {
      "id": "LegacyOrange",
      "tier": "S",
      "name": "Bruno",
      "expansion": "Legacy",
      "title": "Funkenbrecher",
      "abilityName": "Custom",
      "abilityEffect": "In deinem Schritt Aktionen ausführen: Wähle 1 Spieler und wirke 1 seiner gebundenen Zauber. Dieser Zauber: +1 Schaden und er bleibt gebunden. UND Füge 1 Monster deiner Wahl 3 Schaden zu.",
      "charges": "Custom"
    },
    {
      "id": "LegacyBlue",
      "tier": "B",
      "name": "Lanariel",
      "expansion": "Legacy",
      "title": "Kristallhüterin",
      "abilityName": "Custom",
      "abilityEffect": "In deinem Schritt Aktionen ausführen: Jeder andere Spieler zieht 2 Karten. UND Decke alle Reihenfolgekarten auf. Lege sie in einer Reihenfolge deiner Wahl verdeckt zurück.",
      "charges": "Custom"
    },
    {
      "id": "Indira",
      "tier": "D",
      "name": "Indira",
      "expansion": "OD",
      "title": "Riss-Magier-Lehrling",
      "abilityName": "List der Pyromanen",
      "abilityEffect": "In Deinem Spieler-Zug während Zauber wirken: Wirke eine Anzahl Zauber deiner Wahl direkt von deiner Hand. +1 Schaden für jeden so gewirkten Zauber. Dann darfst du 1 Karte deiner Wahl in deinem Ablagestapel zerstören.",
      "charges": 4
    },
    {
      "id": "Remnant",
      "tier": "D",
      "name": "Reliquior",
      "expansion": "OD",
      "title": "Ätherisches Wesen",
      "abilityName": "Hauch des Nichts",
      "abilityEffect": "In Deinem Spieler-Zug während Aktionen ausführen: Wähle 1 anderen Spieler, der 2 Karten von seinem Ablagestapel zurück auf die Hand nimmt. ODER Die Feste der letzten Ruhe heilt 5 Leben.",
      "charges": 5
    },
    {
      "id": "Nook",
      "tier": "C",
      "name": "Nook",
      "expansion": "SD",
      "title": "Orb-Rufer",
      "abilityName": "Ätherische Verdichtung",
      "abilityEffect": "In deinem Spielzug während Aktionen ausführen: Du darfst 1 Karte auf deiner Hand oder in deinem Ablagestapel zerstören. Erhalte 4 Æ. Den nächsten Zauber, den du in diesem Zug erwirbst, darfst du direkt auf die Hand nehmen.",
      "charges": 5
    },
    {
      "id": "Mazra",
      "tier": "A",
      "name": "Mazra",
      "expansion": "TA",
      "title": "Belesene Riss-Magierin",
      "abilityName": "Nachforschungen",
      "abilityEffect": "In deinem Spieler-Zug während Aktionen ausführen: Zerstöre 1 Mazra-Karte auf deiner Hand. Erwirb gratis 1 Mazra-Karte von deinem Forschungs-Stapel, die bis zu 3 Æ mehr kostet. Nimm sie direkt auf die Hand. ODER Nimm alle Mazra-Karten aus deinem Ablagestapel zurück auf die Hand.",
      "charges": 4,
      "gender": "w"
    },
    {
      "id": "Qu",
      "tier": "B",
      "name": "Qu",
      "expansion": "TA",
      "title": "Erbauer und Zerstörerin",
      "abilityName": "Duale Realität",
      "abilityEffect": "In deinem Spieler-Zug während Aktionen ausführen: Bist du in Zerstörerin-Gestalt? Wirke bis zu 2 gebundene Zauber mit unterschiedlichen Namen von 1 oder mehr Spielern. Bist du in Erbauerin-Gestalt? Wähle 1 Spieler, der bis zu 2 Zauber aus seinem Ablagestapel an seine aktiven Risse bindet. Drehe danach dein Gestalt-Plättchen auf die andere Seite.",
      "charges": 5
    },
    {
      "id": "Nym",
      "tier": "D",
      "name": "Nym",
      "expansion": "Depths",
      "title": "Riss-Magier-Lehrling",
      "abilityName": "Barriere",
      "abilityEffect": "In Deinem Spieler-Zug während Aktionen ausführen: Sieh dir die oberste Erzfeind-Karte an und wirf sie ab. Hast du einen ANGRIFF gesehen, wiederhole das (1x).",
      "charges": 5,
      "gender": "m"
    },
    {
      "id": "Reeve",
      "tier": "S",
      "name": "Reeve",
      "expansion": "Depths",
      "title": "Riss-Magier-Elite",
      "abilityName": "Bezwinger-Klinge",
      "abilityEffect": "In Deinem Spieler-Zug während Aktionen ausführen: Füge 1 Monster 5 Schaden zu. Füge 1 anderen Monster 3 Schaden zu.",
      "charges": 4
    },
    {
      "id": "Zhana",
      "tier": "S",
      "name": "Z'hana",
      "expansion": "Depths",
      "title": "Abtrünnige Riss-Magierin",
      "abilityName": "Das Licht Der Welt, Die War",
      "abilityEffect": "In Deinem Spieler-Zug während Aktionen ausführen: Die Feste der letzten Ruhe heilt 7 Leben.",
      "charges": 5,
      "gender": "w"
    },
    {
      "id": "Malastar",
      "tier": "C",
      "name": "Malastar",
      "expansion": "Nameless",
      "title": "Riss-Magier-Mentor",
      "abilityName": "Aetherium-Geschenk",
      "abilityEffect": "In Deinem Spieler-Zug während Aktionen ausführen: Erwirb 1 Zauber deiner Wahl gratis. Du darfst diesen Zauber sofort an den aktiven Riss 1 Spielers deiner Wahl binden.",
      "charges": 6
    },
    {
      "id": "Sahala",
      "tier": "C",
      "name": "Sahala",
      "expansion": "NA",
      "title": "Riss-Magier-Orakel",
      "abilityName": "Sternenband",
      "abilityEffect": "In deinem Spieler-Zug während Zauber wirken oder Aktionen ausführen: Sieh dir die obersten 3 Karten deines Decks an. Siehst du Zauber? Nimm 1 davon auf die Hand. Ist kein Zauber an deinen Gestirn-Riss gebunden? Binde bis zu 2 Zauber von deiner Hand an deinen aktiven Gestirn-Riss.",
      "charges": 4
    },
    {
      "id": "Gygar",
      "tier": "C",
      "name": "Gygar",
      "expansion": "NA",
      "title": "Herr der Gezeiten",
      "abilityName": "Flutwelle",
      "abilityEffect": "In deinem Spieler-Zug während Aktionen ausführen: Lege 1 Flut-Plättchen auf deinen Gezeiten-Riss. ODER Wirke 1 an deinen Gezeiten-Riss gebundenen Zauber. Erhalte 2 Energie.",
      "charges": 5
    },
    {
      "id": "Soskel",
      "tier": "A",
      "name": "Soskel",
      "expansion": "NA",
      "title": "Riss-Magier-Aristokrat",
      "abilityName": "Augeladenes Siegel",
      "abilityEffect": "In deinem Spieler-Zug während Aktionen ausführen: Wähle 1 Spieler. Dann wähle: Lege 1 Aufladung auf einen seiner Risse ohne Aufladung. ODER Lege 1 Aufladung von einem seiner Risse ab. Diese Spieler heilt 4 Leben.",
      "charges": 4
    },
    {
      "id": "Taqren",
      "tier": "B",
      "name": "Taqren",
      "expansion": "NA",
      "title": "Der Schild",
      "abilityName": "Essenz-Manipulation",
      "abilityEffect": "In deinem Spieler-Zug während Aktionen ausführen: Bündele 1 Riss deiner Wahl (bei 1 Spieler deiner Wahl). Wähle 1 Spieler, der 1 Leben für jeden deiner aktiven Risse heilt.",
      "charges": 4
    },
    {
      "id": "Talix",
      "tier": "C",
      "name": "Talix",
      "expansion": "NA",
      "title": "Die Kette",
      "abilityName": "Aufsteigende Asche",
      "abilityEffect": "In deinem Spieler-Zug während Aktionen ausführen: Die Feste heilt 5 Leben. ODER Zerstöre 2 Funken auf deiner Hand. Ist das passiert? Mische deine Reihenfolgekarte in das Reihenfolgedeck.",
      "charges": 5
    },
    {
      "id": "Rhia",
      "tier": "B",
      "name": "Rhia",
      "expansion": "NA",
      "title": "Riss-Magier-Schatzjägerin",
      "abilityName": "Transformation",
      "abilityEffect": "In deinem Spieler-Zug während Aktionen ausführen: Lege 1 Karte von deiner Hand oder deinem Ablagestapel zurück auf ihren Vorrat. War es ein Artefakt? Erwirb gratis 1 Karte, die bis zu 3 Æ mehr kostet. Andernfalls erwirb gratis 1 Karte, die bis zu 2 Æ mehr kostet. Nimm die Karte immer direkt auf die Hand.",
      "charges": 4,
      "gender": "w"
    },
    {
      "id": "Claudia",
      "tier": "S",
      "name": "Claudia",
      "expansion": "NA",
      "title": "Riss-Magier-Prospektorin",
      "abilityName": "Ätherplosion",
      "abilityEffect": "Im Spieler-Zug eines anderen Spielers während Aktionen ausführen: Dieser Spieler erhält 2 Æ. Wenn er das nächste Mal in diesem Zug eine Karte erwirbt, erwirbst du gratis 1 Karte des gleichen Vorrats. ODER Der Spieler erhält 5 Æ.",
      "charges": 5,
      "gender": "w"
    },
    {
      "id": "Lost",
      "tier": "S",
      "name": "Lost",
      "expansion": "NA",
      "title": "Lebendige Schmiede",
      "abilityName": "Hörnchens Stärke",
      "abilityEffect": "In deinem Spieler-Zug während Aktionen ausführen: Nimm bis zu 4 Karten mit Kosten von 0 Æ aus deinem Ablagestapel zurück auf die Hand.",
      "charges": 5
    },
    {
      "id": "Sparrow",
      "tier": "D",
      "name": "Sparrow",
      "expansion": "TV",
      "title": "Riss-Magier-Soldatin",
      "abilityName": "Arkane Verbindung",
      "abilityEffect": "In Deinem Spieler-Zug während Aktionen ausführen: Wähle 4x je 1 Spieler und bündele 1 seiner Risse. ODER Wähle 1 anderen Spieler ohne dunkle Risse. Dieser Spieler zieht 3 Karten und bindet dann bis zu 3 Zauber seiner Wahl von der Hand an seine Risse.",
      "charges": 5,
      "gender": "w"
    },
    {
      "id": "XaxosTV",
      "tier": "D",
      "name": "Xaxos",
      "expansion": "TV",
      "title": "Herold der Leere",
      "abilityName": "Schein der Praetorianer",
      "abilityEffect": "In Deinem Spieler-Zug während Aktionen ausführen: Wähle 1 anderen Spieler, der 1 Energie erhält und 1 zufällige Karte von seiner Hand abwirft. Bündele 1 deiner Risse. Heile 1 Leben. Zerstöre 1 Karte deiner Wahl auf deiner Hand oder in deinem Ablagestapel.",
      "charges": 4
    },
    {
      "id": "Dezmodia",
      "tier": "C",
      "name": "Dezmodia",
      "expansion": "WE",
      "title": "Wunderkind der Leere",
      "abilityName": "Sturmwind-Sigille",
      "abilityEffect": "In Deinem Spieler-Zug während Aktionen ausführen: Wähle 1 Spieler, der 1 seiner aktiven Risse I oder II mit 1 deiner entsprechenden Sigillen-Risse ersetzt. Gebundene Zauber kommen zurück auf die Hand. Dann darf dieser Spieler sofort 1 Zauber seiner Wahl von der Hand an seine Risse binden.",
      "charges": 6
    },
    {
      "id": "Garu",
      "tier": "C",
      "name": "Garu",
      "expansion": "WE",
      "title": "Vereidigter Beschützer",
      "abilityName": "Kolossale Kraft",
      "abilityEffect": "In Deinem Spieler-Zug während Aktionen ausführen: Wirf bis zu 4 deiner gebundenen Zauber ab. Füge 2 Schaden zu. +X Schaden. X = 4 pro gerade abgeworfenem Zauber. Dieser Schaden ist aufteilbar.",
      "charges": 5
    },
    {
      "id": "Gex",
      "tier": "A",
      "name": "Gex",
      "expansion": "WE",
      "title": "Riss-Magier-Beraterin",
      "abilityName": "Vimkunst-Schwur",
      "abilityEffect": "In Deinem Spieler-Zug während Aktionen ausführen: Wähle bis zu 2 Karten in deinem Ablagestapel mit Æ-Kosten von 0. Zerstöre sie. Wähle 1 anderen Spieler, der 1 Karte zieht und 2 Leben heilt.",
      "charges": 5,
      "gender": "w"
    },
    {
      "id": "Mazahaedron",
      "tier": "B",
      "name": "Mazahaedron",
      "expansion": "WE",
      "title": "Steinkreis-Mystiker",
      "abilityName": "Untererde-Mantra",
      "abilityEffect": "In Deinem Spieler-Zug während Aktionen ausführen: Du darfst gratis 1 Kristall mit Æ-Kosten von 4 oder weniger erwerben. Die Feste der letzten Ruhe heilt 4 Leben.",
      "charges": 4
    },
    {
      "id": "MistWE",
      "tier": "B",
      "name": "Mist",
      "expansion": "WE",
      "title": "Leeren-Schreiter",
      "abilityName": "Gesegnetes Brandmal",
      "abilityEffect": "In Deinem Spieler-Zug während Zauber wirken: Wähle bis zu 3 gebundene Zauber auf den Rissen der Spieler. Wirke sie. Nach jedem Wirken dieser Zauber: Wähle 1 anderen Spieler, der diesen Zauber auf die Hand nimmt (das muss nicht der Spieler sein, bei dem er gebunden war).",
      "charges": 6,
      "gender": "w"
    },
    {
      "id": "Quilius",
      "tier": "D",
      "name": "Quilius",
      "expansion": "WE",
      "title": "Riss-Magier-Assassine",
      "abilityName": "Quietus-Gelübde",
      "abilityEffect": "In Deinem Spieler-Zug während Aktionen ausführen: Füge X Schaden zu. X = 2 pro Trophäe.",
      "charges": 5
    },
    {
      "id": "Ulgimor",
      "tier": "D",
      "name": "Ulgimor",
      "expansion": "WE",
      "title": "Schattenhaut-Biest",
      "abilityName": "Eidolon-Schleier",
      "abilityEffect": "In Deinem Spieler-Zug während Aktionen ausführen: Heile 6 Leben. Bist du ERSCHÖPFT? Wähle stattdessen 1 anderen Spieler, der 5 Leben heilt.",
      "charges": 6
    },
    {
      "id": "YanMagda",
      "tier": "B",
      "name": "Yan Magda",
      "expansion": "WE",
      "title": "Erleuchtete im Exil",
      "abilityName": "Kaiserliches Ritual",
      "abilityEffect": "In Deinem Spieler-Zug während Aktionen ausführen: Erwirb gratis 1 Karte von 1 Vorrat deiner Wahl. Hast du 4 aktive Risse? Wähle 1 anderen Spieler. Dieser Spieler erwirbt gratis 1 Karte von 1 Vorrat seiner Wahl, die er oben auf sein Deck legt.",
      "charges": 5,
      "gender": "w"
    }
  ],
  "nemeses": [
    {
      "id": "CarapaceQueen",
      "name": "Carapax-Königin",
      "expansion": "AE",
      "health": 60,
      "difficulty": 3,
      "expeditionRating": 1    },
    {
      "id": "CrookedMask",
      "name": "König der Masken",
      "expansion": "AE",
      "health": 70,
      "difficulty": 5,
      "expeditionRating": 2    },
    {
      "id": "PrinceOfGluttons",
      "name": "Der Unersättliche",
      "expansion": "AE",
      "health": 70,
      "difficulty": 5,
      "expeditionRating": 2    },
    {
      "id": "Rageborne",
      "name": "Hassgeburt",
      "expansion": "AE",
      "health": 70,
      "difficulty": 2,
      "expeditionRating": 1    },
    {
      "id": "Necroswarm",
      "name": "Nekroschwarm",
      "expansion": "IW",
      "health": 70,
      "difficulty": 7,
      "expeditionRating": 4    },
    {
      "id": "Bladius",
      "name": "Bladius",
      "expansion": "Legacy",
      "health": 40,
      "difficulty": 1,
      "expeditionRating": 1    },
    {
      "id": "Deathmind",
      "name": "Gedankenschlächter",
      "expansion": "Legacy",
      "health": 80,
      "difficulty": 6,
      "expeditionRating": 4    },
    {
      "id": "FungalMesh",
      "name": "Grosser Todling",
      "expansion": "Legacy",
      "health": 70,
      "difficulty": 4,
      "expeditionRating": 2    },
    {
      "id": "MaelstromRisen",
      "name": "Maelstrom: Wiederkehrer",
      "expansion": "Legacy",
      "health": 65,
      "difficulty": 8,
      "expeditionRating": 4    },
    {
      "id": "SpawningHorror",
      "name": "Brutegel",
      "expansion": "Legacy",
      "health": 50,
      "difficulty": 3,
      "expeditionRating": 1    },
    {
      "id": "XaxosAscended",
      "name": "Xaxos: Entfesselt",
      "expansion": "Legacy",
      "health": 90,
      "difficulty": 9,
      "expeditionRating": 4    },
    {
      "id": "HazeFiend",
      "name": "Herr der Schleier",
      "expansion": "Legacy",
      "health": 75,
      "difficulty": 5,
      "expeditionRating": 2    },
    {
      "id": "ThriceDeadProphet",
      "name": "Dreimaltoter Prophet",
      "expansion": "OD",
      "health": 40,
      "difficulty": 5,
      "expeditionRating": 2    },
    {
      "id": "Wraithmonger",
      "name": "Traum-Händler",
      "expansion": "OD",
      "health": 70,
      "difficulty": 6,
      "expeditionRating": 4    },
    {
      "id": "TheWailing",
      "name": "Donnerkreisch",
      "expansion": "SD",
      "health": 50,
      "difficulty": 6,
      "expeditionRating": 3    },
    {
      "id": "TheWanderer",
      "name": "Der Wanderer",
      "expansion": "TA",
      "health": 40,
      "difficulty": 5,
      "expeditionRating": 3    },
    {
      "id": "HordeCrone",
      "name": "Horden-Muhme",
      "expansion": "Depths",
      "health": 60,
      "difficulty": 6,
      "expeditionRating": 2    },
    {
      "id": "BlightLord",
      "name": "Lord des Verderbens",
      "expansion": "Nameless",
      "health": 70,
      "difficulty": 4,
      "expeditionRating": 2    },
    {
      "id": "WaywardOne",
      "name": "Der Wegbereiter",
      "expansion": "Nameless",
      "health": 60,
      "difficulty": 7,
      "expeditionRating": 3    },
    {
      "id": "Maggoth",
      "name": "Madrox",
      "expansion": "NA",
      "health": 45,
      "difficulty": 3,
      "expeditionRating": 1    },
    {
      "id": "Arachnos",
      "name": "Arachnos",
      "expansion": "NA",
      "health": 70,
      "difficulty": 4,
      "expeditionRating": 2    },
    {
      "id": "AgelessWalker",
      "name": "Ewigtoter",
      "expansion": "NA",
      "health": 80,
      "difficulty": 5,
      "expeditionRating": 3    },
    {
      "id": "Fenrix",
      "name": "Fenrix",
      "expansion": "NA",
      "health": 60,
      "difficulty": 7,
      "expeditionRating": 4    },
    {
      "id": "KnightOfShackles",
      "name": "Ritter des Schreckens",
      "expansion": "TV",
      "health": 70,
      "difficulty": 4,
      "expeditionRating": 1    },
    {
      "id": "MaidenOfThorns",
      "name": "Dornen-Maid",
      "expansion": "TV",
      "health": 80,
      "difficulty": 4,
      "expeditionRating": 3    },
    {
      "id": "GateWitch",
      "name": "Riss-Furie",
      "expansion": "WE",
      "health": 70,
      "difficulty": 7,
      "expeditionRating": 4    },
    {
      "id": "HollowCrown",
      "name": "Krone der Leere",
      "expansion": "WE",
      "health": 1,
      "difficulty": 5,
      "expeditionRating": 3    },
    {
      "id": "MagusOfCloaks",
      "name": "Schattenmantel-Magus",
      "expansion": "WE",
      "health": 35,
      "difficulty": 7,
      "expeditionRating": 3    },
    {
      "id": "UmbraTitan",
      "name": "Schatten-Titan",
      "expansion": "WE",
      "health": 70,
      "difficulty": 3,
      "expeditionRating": 1    }
  ],
  "treasures": [
    { "id": "DezmodiasOblivionShard", "name": "Dezmodias Nihil-Scherbe", "expansion": "IW", "level": 1, "subtype": "Gem", "effect": "Erhalte 2 <span class=\"aether\">&AElig;</span>, aber nicht zum Erwerb von Artefakten oder Zaubern." },
    { "id": "UlgimorsCoalFragment", "name": "Ulgimors Kohlen-Fragment", "expansion": "IW", "level": 1, "subtype": "Gem", "effect": "Erhalte 2 <span class=\"aether\">&AElig;</span> und erleide 1 Schaden. <span class=\"or\">OR</span> Heile 1 Leben." },
    { "id": "IndirasLoneOpal", "name": "Indiras Einsamer Opal", "expansion": "IW", "level": 1, "subtype": "Gem", "effect": "Erhalte 1 <span class=\"aether\">&AElig;</span>.<br/> Du darfst 1 Zauber mit <span class=\"aether\">&AElig;</span>-Kosten von 4 oder weniger von der Hand wirken." },
    { "id": "MistsAmethystParagon", "name": "Mists Makellose Amethyst-Scherbe", "expansion": "IW", "level": 1, "subtype": "Gem", "effect": "Erhalte 1 <span class=\"aether\">&AElig;</span>.<br/> Wähle 1 anderen Spieler. Dieser Spieler darf 1 Zauber seiner Wahl von der Hand an seine (auch dunklen) Risse binden." },
    { "id": "MalastarsImmolate", "name": "Malastars Brennende Luft", "expansion": "IW", "level": 1, "subtype": "Spell", "effect": "<b>Gebunden:</b> Immer wenn du 1 oder mehr Leben verlierst, erhalte 1 Energie.<br/> <b>Wirken:</b> Füge 1 Schaden zu." },
    { "id": "YanMagdasIlluminate", "name": "Yan Magdas Erleuchtung", "expansion": "IW", "level": 1, "subtype": "Spell", "effect": "<b>Gebunden:</b> Aktivierst oder bündelst du 1 deiner Risse in deinem Zug? Füge 1 Schaden zu.<br/> <b>Wirken:</b> Füge 1 Schaden zu." },
    { "id": "EyeOfTheMaelstrom", "name": "Auge des Malstroms", "expansion": "IW", "level": 2, "subtype": "", "effect": "<b>Im Spielaufbau:</b><br/> Legt diese Karte neben einen Vorrat mit <span class=\"aether\">&AElig;</span>-Kosten von 4 oder mehr. <b>Immer wenn ein Spieler eine Karte dieses Vorrats erwirbt:</b><br/> Dieser Spieler heilt 1 Leben." },
    { "id": "WellOfDespair", "name": "Brunnen der Verzweiflung", "expansion": "IW", "level": 2, "subtype": "", "effect": "<b>Immer wenn ein Spieler dem Erzfeind mit einem einzelnen Zauber insgesamt 6 oder mehr Schaden zufügt:</b><br/> Legt 1 Zeitmarker hierauf.<br/> <span class=\"hint\">(Hinweis: Hierbei werden mehrere Schadensquellen eines Zaubers zusammengezählt.)</span> <b>Zu Beginn des Erzfeind-Zuges:</b><br/> Fügt dem Erzfeind X Schaden zu. X = Anzahl Zeitmarker hierauf." },
    { "id": "CronesAmulet", "name": "Amulett der Muhme", "expansion": "IW", "level": 2, "subtype": "", "effect": "<b>Immer wenn ein Spieler einen Riss aktiviert:</b><br/> Dieser Spieler darf 1 Karte auf seiner Hand zerstören." },
    { "id": "EdibleFungusChunks", "name": "Geniessbare Pilzhappen", "expansion": "IW", "level": 2, "subtype": "", "effect": "<b>Immer wenn ein Spieler Leben heilt:</b><br/> Dieser Spieler heilt +1 Leben." },
    { "id": "UmbralHornOfWar", "name": "Kriegshorn des Schattens", "expansion": "IW", "level": 2, "subtype": "", "effect": "<b>Im Spielaufbau:</b><br/> Legt diese Karte neben einen Zauber-Vorrat mit <span class=\"aether\">&AElig;</span>-Kosten von 6 oder mehr. <b>Dauerhaft:</b><br/> Zauber dieses Vorrats fügen +2 Schaden zu, wenn sie gewirkt werden." },
    { "id": "TheBrokenMask", "name": "Maske des Königs", "expansion": "IW", "level": 2, "subtype": "", "effect": "<b>Immer nachdem ein Spieler seine Spezialfähigkeit eingesetzt hat:</b><br/> Dieser Spieler wählt 1 anderen Spieler, der 1 Energie erhält." },
    { "id": "AlchemistsAlembic", "name": "Alchemistischer Destillier-Kolben", "expansion": "IW", "level": 3, "subtype": "", "effect": "<b>In deinem Schritt <i>Aktionen ausführen</i> (1x pro Zug):</b><br/> Wenn du zum zweiten Mal in diesem Zug ein Artefakt oder einen Kristall mit <span class=\"aether\">&AElig;</span>-Kosten von jeweils 4 oder mehr spielst: Füge 3 Schaden zu." },
    { "id": "SoothsayersPouch", "name": "Beutel des Wahrsagers", "expansion": "IW", "level": 3, "subtype": "", "effect": "<b>Im Spielaufbau:</b><br/> Wähle 1 weiteren Schatz der Stufe 1 und füge ihn deinem STARTDECK hinzu.<br/><br/> Als Gruppe dürft ihr 1 weiteren Schatz der Stufe 2 wählen.<br/><br/> Für beides gelten die normalen Schatz-Regeln." },
    { "id": "SuppressingPin", "name": "Stecknadel der Unterbindung", "expansion": "IW", "level": 3, "subtype": "", "effect": "<b>In deinem Schritt <i>Aktionen ausführen</i> (1x pro Zug):</b><br/> Du darfst 1 Karte deiner Wahl von der Hand abwerfen. Tust du das? Wähle 1 anderen Spieler, der 1 Karte zieht, und du darfst 1 Zeitmarker auf einen PLAN in der Auslage legen." },
    { "id": "Quicksilver", "name": "Quecksilber", "expansion": "IW", "level": 3, "subtype": "", "effect": "<b>Immer wenn du einen Zauber mit <span class=\"aether\">&AElig;</span>-Kosten von 2 oder mehr wirkst:</b><br/> Du darfst 1 anderen Spieler wählen, der den gewirkten Zauber auf die Hand nimmt (statt ihn auf deinen Ablagestapel zu legen)." },
    { "id": "BandOfRetrieval", "name": "Kordel der Rückholung", "expansion": "IW", "level": 3, "subtype": "", "effect": "<b>Zu Beginn deines Schritts <i>Zauber wirken</i>:</b><br/> Wirfst du jetzt 1 Energie ab? Den nächsten Zauber, den du in diesem Schritt wirkst, nimmst du zuürck auf die Hand (statt auf den Ablagestapel)." },
    { "id": "PurifiedBangle", "name": "Geläuterter Armreif", "expansion": "IW", "level": 3, "subtype": "", "effect": "<b>In deinem Schritt <i>Aktionen ausführen</i> (1x pro Zug):</b><br/> Du darfst 9 <span class=\"aether\">&AElig;</span> bezahlen und 1 Schaden erleiden. Tust du das? Lege 1 Erzfeind Karte in der Auslage zurück auf den Erzfeind-Stapel." },
    { "id": "MazahaedronsWorldheartShard", "name": "Mazahaedrons Weltherz-Scherbe", "expansion": "SD", "level": 1, "subtype": "Gem", "effect": "Erhalte 1 <span class=\"aether\">&AElig;</span>. <span class=\"or\">OR</span> Erhalte 2 <span class=\"aether\">&AElig;</span>, aber nur zum Erwerb einer Karte. Die nächste Karte, die du erwirbst, legst du auf den Ablagestapel 1 anderen Spielers deiner Wahl." },
    { "id": "PhaedraxasTourmalineShard", "name": "Phaedraxas Turmalin-Scherbe", "expansion": "SD", "level": 1, "subtype": "Gem", "effect": "Erhalte 1 <span class=\"aether\">&AElig;</span>.<br/> Wähle 1 anderen Spieler. Dieser Spieler darf 1 Schaden erleiden um 1 Karte seiner Wahl auf der Hand zu zerstören." },
    { "id": "FracturedShell", "name": "Zerbrochene Hülle", "expansion": "SD", "level": 2, "subtype": "", "effect": "<b>Im Spielaufbau:</b><br/> Legt diese Karte neben einen Vorrat mit <span class=\"aether\">&AElig;</span>-Kosten von 4 oder mehr.<br/><br/> <b>Immer wenn ein Spieler eine Karte dieses Vorrats erwirbt:</b><br/> Dieser Spieler erhält 1 Energie." },
    { "id": "Extra-DimensionalLens", "name": "Extra-Dimensionale Linse", "expansion": "SD", "level": 3, "subtype": "", "effect": "<b>In deinem Schritt <i>Aktionen ausführen</i> (1x pro Zug):</b><br/> Du darfst dir die obersten 3 Karten des Erzfeind-Stapels ansehen. Lege sie in einer Reihenfolge deiner Wahl zurück." },
    { "id": "SeersBracer", "name": "Armschienen des Sehers", "expansion": "SD", "level": 3, "subtype": "", "effect": "<b>Wenn du in deinem Schritt <i>Aktionen ausführen</i> 1 Energie erhältst (1x pro Zug):</b><br/> Wähle 1 anderen Spieler, der 1 Karte zieht." },
    { "id": "RemnantsVoidShard", "name": "Reliquiors Leere-Scherbe", "expansion": "TA", "level": 1, "subtype": "Gem", "effect": "Erhalte 1 <span class=\"aether\">&AElig;</span>.<br/> Erhalte 1 <span class=\"aether\">&AElig;</span>, aber nur zum Bündeln oder Aktivieren eines Risses." },
    { "id": "QuiliussErasure", "name": "Quilius' Beseitigung", "expansion": "TA", "level": 1, "subtype": "Spell", "effect": "<b>Wirken:</b> Füge 1 Schaden zu.<br/> Fügst du damit einem MONSTER Schaden zu? +1 Schaden." },
    { "id": "ZhanasFleetingEmber", "name": "Z'hanas Flüchtige Glut", "expansion": "TA", "level": 1, "subtype": "Spell", "effect": "<b>Wirken:</b> Füge 1 Schaden zu. <span class=\"or\">OR</span> <b>Wirken:</b> Wirke 1 anderen deiner gebundenen Zauber mit <span class=\"aether\">&AElig;</span>-Kosten von 4 oder weniger. Der Zauber bleibt gebunden." },
    { "id": "BlightedRootClump", "name": "Verdorbener Wurzelballen", "expansion": "TA", "level": 2, "subtype": "", "effect": "<b>Immer wenn die letzte Karte eines Vorrats erworben oder zerstört wird:</b><br/> Wählt 1 Spieler, der 3 Leben heilt." },
    { "id": "PetrifiedWitchFinger", "name": "Erstarrter Finger der Furie", "expansion": "TA", "level": 2, "subtype": "", "effect": "<b>Immer wenn die letzte Karte eines Vorrats erworben oder zerstört wird:</b><br/> Wählt 1 Spieler, der 3 Energie erhält." },
    { "id": "WaywardScraps", "name": "Überreste des Wegbereiters", "expansion": "TA", "level": 2, "subtype": "", "effect": "<b>Im Schritt <i>Aktionen ausführen</i> jedes Spieler-Zuges (1x pro Zug):</b><br/> Du darfst 4 <span class=\"aether\">&AElig;</span> bezahlen. Tust du das? Bündele jeden Riss IV (bei allen Spielern)." },
    { "id": "TrueSightMonocle", "name": "Monokel der Klarsicht", "expansion": "TA", "level": 3, "subtype": "", "effect": "<b>Zu Beginn deines Schrittes <i>Aktionen ausführen</i>:</b><br/> Sind 6 oder mehr Karten in deinem Ablagestapel? Erhalte 2 <span class=\"aether\">&AElig;</span>." },
    { "id": "EntwinedAetherStrands", "name": "Verschlungene Ätherstränge", "expansion": "TA", "level": 3, "subtype": "", "effect": "<b>Am Ende deines Schrittes <i>Karten ziehen</i>:</b><br/> Du darfst 1 Karte deiner Wahl von der Hand ablegen und 1 Karte ziehen." },
    { "id": "SiphoningBlade", "name": "Kanalisierende Klinge", "expansion": "TA", "level": 3, "subtype": "", "effect": "<b>Wenn du einen Riss bündelst oder aktivierst (1x pro Zug):</b><br/> Erhalte 1 Energie." },
    { "id": "GemEncrustedAnklet", "name": "Kristallverkrustete Fusskette", "expansion": "TA", "level": 3, "subtype": "", "effect": "<b>Einmalig zu Beginn deines ersten Zuges:</b><br/> Erhalte 3 <span class=\"aether\">&AElig;</span>." },
    { "id": "KadirsEmeraldShard", "name": "Kadirs Smaragd-Scherbe", "expansion": "NA", "level": 1, "subtype": "Gem", "effect": "Erhalte 1 <span class=\"aether\">&AElig;</span>. <span class=\"or\">OR</span> Wähle 1 Spieler, der 1 Leben heilt." },
    { "id": "GexsShatteredGeode", "name": "Gex' Bruchgeoden-Scherbe", "expansion": "NA", "level": 1, "subtype": "Gem", "effect": "Erhalte 1 <span class=\"aether\">&AElig;</span>.<br/> Wähle 1 anderen Spieler. Du darfst die oberste Karte seines Ablagestapels auf die Hand nehmen." },
    { "id": "JiansMoonstoneShard", "name": "Jians Mondstein-Scherbe", "expansion": "NA", "level": 1, "subtype": "Gem", "effect": "Erhalte 1 <span class=\"aether\">&AElig;</span>.<br/> Erhalte 1 <span class=\"aether\">&AElig;</span>, aber nur zum Erwerb von Kristallen." },
    { "id": "LashsQuartzShard", "name": "Lashs Quartz-Scherbe", "expansion": "NA", "level": 1, "subtype": "Gem", "effect": "Erhalte 1 <span class=\"aether\">&AElig;</span>.<br/> Sieh dir die oberste Karte des Reihenfolgedecks an. Siehst du eine Spieler-Reihenfolgekarte? Erhalte 1 <span class=\"aether\">&AElig;</span>. Dann darfst du die angesehene Karte unter das Deck schieben." },
    { "id": "XaxosFlare", "name": "Xaxos' Leuchtfeuer", "expansion": "NA", "level": 1, "subtype": "Spell", "effect": "<b>Wirken:</b> Füge 1 Schaden zu.<br/> Sieh dir die oberste Karte des Reihenfolgedecks an. Siehst du eine Spieler-Reihenfolgekarte? +2 Schaden." },
    { "id": "AdelheimsAmethystShard", "name": "Adelheims Amethyst-Scherbe", "expansion": "NA", "level": 1, "subtype": "Gem", "effect": "Erhalte 1 <span class=\"aether\">&AElig;</span>.<br/> Wähle 1 anderen Spieler. Dieser Spieler darf 1 Karte ziehen und dann 1 Karte seiner Wahl von der Hand abwerfen." },
    { "id": "BramasBuriedLight", "name": "Bramas Verschüttetes Licht", "expansion": "NA", "level": 1, "subtype": "Spell", "effect": "<b>Wirken:</b> Füge 1 Schaden zu.<br/> Erhalte 1 <span class=\"aether\">&AElig;</span> im Schritt <i>Aktionen ausführen.</i>" },
    { "id": "GarusTorch", "name": "Garus Fackel", "expansion": "NA", "level": 1, "subtype": "Spell", "effect": "<b>Wirken:</b> Füge 1 Schaden zu.<br/> <span class=\"or\">OR</span> <b>Wirken:</b> Bündele 1 Riss deiner Wahl (bei 1 Spieler deiner Wahl)." },
    { "id": "XaxosPyre", "name": "Xaxos' Scheiterhaufen", "expansion": "NA", "level": 1, "subtype": "Spell", "effect": "<b>Wirken:</b> Füge 1 Schaden zu.<br/> Wirft 1 anderer Spieler 1 Karte seiner Wahl von der Hand ab? +2 Schaden." },
    { "id": "MistsGarnetShard", "name": "Mists Granatium-Scherbe", "expansion": "NA", "level": 1, "subtype": "Gem", "effect": "Erhalte 1 <span class=\"aether\">&AElig;</span>. <span class=\"or\">OR</span> Wähle 1 Spieler und wirke 1 seiner gebundenen Zauber." },
    { "id": "ShimmeringCloakOfTheMagus", "name": "Schimmernder Mantel des Magus", "expansion": "NA", "level": 2, "subtype": "", "effect": "<b>Immer nachdem ein Spieler seine Spezialfähigkeit eingesetzt hat:</b><br/> Dieser Spieler fügt 2 Schaden zu." },
    { "id": "ImbuedShackles", "name": "Durchströmte Ketten", "expansion": "NA", "level": 2, "subtype": "", "effect": "<b>Im Spielaufbau:</b><br/> Legt diese Karte neben einen Vorrat mit <span class=\"aether\">&AElig;</span>-Kosten von 7 oder mehr. <b>Dauerhaft:</b><br/> Es kostet 1 <span class=\"aether\">&AElig;</span> weniger, eine Karte dieses Vorrats zu erwerben." },
    { "id": "GluttonsTooth", "name": "Zahn des Unersättlichen", "expansion": "NA", "level": 2, "subtype": "", "effect": "<b>Immer wenn die letzte Karte eines Vorrats erworben oder zerstört wird:</b><br/> Wählt 1 Spieler, der 6 Schaden zufügt." },
    { "id": "CoreOfRage", "name": "Kern des Hasses", "expansion": "NA", "level": 2, "subtype": "", "effect": "<b>Im Spielaufbau:</b><br/> Legt diese Karte neben einen Artefakt- oder Zauber-Vorrat eurer Wahl. <b>Immer wenn ein Spieler eine Karte dieses Vorrats erwirbt:</b><br/> Dieser Spieler fügt 2 Schaden zu." },
    { "id": "CleansingAmulet", "name": "Reinigendes Amulett", "expansion": "NA", "level": 2, "subtype": "", "effect": "<b>Immer nachdem ein Spieler seine Spezialfähigkeit eingesetzt hat:</b><br/> Wählt 1 Spieler, der 1 Karte auf seiner Hand zerstören darf." },
    { "id": "CarapaceFragement", "name": "Carapax-Fragment", "expansion": "NA", "level": 2, "subtype": "", "effect": "<b>Im Spielaufbau:</b><br/> Legt diese Karte neben einen Artefakt- oder Zauber-Vorrat eurer Wahl. <b>Immer wenn ein Spieler eine Karte dieses Vorrats erwirbt:</b><br/> Dieser Spieler bündelt 1 seiner Risse." },
    { "id": "ThornedWhip", "name": "Dornenpeitsche", "expansion": "NA", "level": 2, "subtype": "", "effect": "<b>Immer wenn ein Spieler einen Riss aktiviert:</b><br/> Dieser Spieler fügt 2 Schaden zu." },
    { "id": "BonesOfDeathmind", "name": "Knochen des Gedankenschlächters", "expansion": "NA", "level": 2, "subtype": "", "effect": "<b>Immer wenn ein Spieler einen Riss aktiviert:</b><br/> Dieser Spieler erhält 1 Energie. <b>Zu Beginn jedes Spieler-Zuges:</b><br/> Hast du keinen dunklen Riss? Erhalte 1 Energie." },
    { "id": "AcceleratingGauntlets", "name": "Schnelligkeits-Handschuhe", "expansion": "NA", "level": 3, "subtype": "", "effect": "<b>Einmalig zu Beginn deines ersten Zuges:</b><br/> Erwirb gratis 1 Karte mit <span class=\"aether\">&AElig;</span>-Kosten von 4 oder weniger." },
    { "id": "EssenceExtractor", "name": "Essenz-Extraktor", "expansion": "NA", "level": 3, "subtype": "", "effect": "<b>Immer wenn du einen Kristall mit <span class=\"aether\">&AElig;</span>-Kosten von 5 oder mehr ausspielst:</b><br/> Erhalte 1 <span class=\"aether\">&AElig;</span>." },
    { "id": "BroochOfAttunment", "name": "Brosche der Einstimmung", "expansion": "NA", "level": 3, "subtype": "", "effect": "<b>Wenn du einen Zauber mit <span class=\"aether\">&AElig;</span>-Kosten von 6 oder mehr wirkst (1x pro Zug):</b><br/> Erhalte 2 Energie." },
    { "id": "BladedCrystal", "name": "Klingenkristall", "expansion": "NA", "level": 3, "subtype": "", "effect": "<b>Immer wenn du dem Erzfeind Schaden durch einen Zauber zufügst:</b><br/> Dieser Zauber fügt +1 Schaden zu." },
    { "id": "PrismOfDestruction", "name": "Prisma der Zerstörung", "expansion": "NA", "level": 3, "subtype": "", "effect": "<b>Dauerhaft:</b><br/> Wenn du keine dunklen Risse hast, fügt jeder von dir gewirkte Zauber +2 Schaden zu." },
    { "id": "ForgottenTrinket", "name": "Vergessenes Kleinod", "expansion": "NA", "level": 3, "subtype": "", "effect": "<b>Einmalig zu Beginn deines ersten Zuges:</b><br/> Bündele jeden deiner dunklen Risse 1-mal." },
    { "id": "PrecisionMagnifier", "name": "Präzisionslupe", "expansion": "NA", "level": 3, "subtype": "", "effect": "<b>Dauerhaft:</b><br/> Jeder Zauber mit <span class=\"aether\">&AElig;</span>-Kosten von 2 oder mehr, den du wirkst, fügt +1 Schaden zu." },
    { "id": "ShroudOfObfucation", "name": "Totenhemd der Verschleierung", "expansion": "NA", "level": 3, "subtype": "", "effect": "<b>Wenn du in deinem Schritt <i>Zauber wirken</i> 2 oder mehr Zauber wirkst:</b><br/> Erhalte 2 <span class=\"aether\">&AElig;</span>." },
    { "id": "VerdantStaff", "name": "Ranken-Stab", "expansion": "NA", "level": 3, "subtype": "", "effect": "<b>Immer wenn du einen Zauber erwirbst:</b><br/> Heile 1 Leben." },
    { "id": "FlowingMantle", "name": "Wallender Mantel", "expansion": "NA", "level": 3, "subtype": "", "effect": "<b>Zu Beginn deines Zuges:</b><br/> Erhalte 1 <span class=\"aether\">&AElig;</span>, aber nur zum Erwerb von Artefakten. <b>Immer wenn du ein Artefakt erwirbst:</b><br/> Du darfst es oben auf dein Deck legen." },
    { "id": "ReevesRavenShard", "name": "Reeves Raben-Scherbe", "expansion": "promos", "level": 1, "subtype": "Gem", "effect": "Erhalte 1 <span class=\"aether\">&AElig;</span>. Wirfst du jetzt 1 Karte deiner Wahl von der Hand ab? Erhalte 1 <span class=\"aether\">&AElig;</span>." },
    { "id": "NymsVision", "name": "Nyms Vorhersehung", "expansion": "promos", "level": 1, "subtype": "Spell", "effect": "<b>Wirken:</b> Füge 1 Schaden zu.<br /> Sieh dir die oberste Karte des Erzfeind-Stapels an. Ist es ein ANGRIFF? Ehalte 2 <span class=\"aether\">&AElig;</span>." },
    { "id": "SparrowsAid", "name": "Sparrows Hilfe", "expansion": "promos", "level": 1, "subtype": "", "effect": "<b>Wirken:</b> Füge 1 Schaden zu.<br /> Wähle 1 anderen Spieler. Dieser Spieler darf 1 Zauber seiner Wahl von der Hand an seine (auch dunklen) Risse binden." },
    { "id": "WraithsEssence", "name": "Essenz des Traum-Händlers", "expansion": "promos", "level": 2, "subtype": "", "effect": "<b>Dauerhaft:</b><br/> Führt keinerlei Schritte aus, wenn ein Spieler ERSCHÖPFT wird.<br/> Ihr verliert nicht, wenn alle Spieler ERSCHÖPFT sind." },
    { "id": "VolatileClasp", "name": "Schnapp-Halterung", "expansion": "promos", "level": 3, "subtype": "", "effect": "<b>Immer wenn du ein Artefakt mit <span class=\"aether\">&AElig;</span>-Kosten von 4 oder mehr ausspielst:</b><br/> Wähle 1 anderen Spieler, der 1 Energie erhält." },
    { "id": "FangedChoker", "name": "Stachelbewehrter Halsreif", "expansion": "promos", "level": 3, "subtype": "", "effect": "<b>Nach deinem Schritt <i>Karten ziehen</i>:</b><br/> Sind die <span class=\"aether\">&AElig;</span>-Kosten der Zauber auf deiner Hand zusammen 6 oder mehr? Ziehe 1 Karte." },
    { "id": "EndlessBandolier", "name": "Endloser Brustgürtel", "expansion": "promos", "level": 3, "subtype": "", "effect": "<b>In deinem Schritt <i>Aktionen ausführen (1x pro Zug):</i></b><br/> Du darfst 1 Karte deiner Wahl von der Hand abwerfen. Tust du das? Füge 1 Schaden zu und erhalte 1 Energie." }
  ],
  "marketplaceCards": [
    { "id": "DiamondCluster", "name": "Rohdiamant", "expansion": "AE", "subtype": "Kristall", "cost": 4, "effect": "Erhalte 2 Æ. Ist dies dein genau zweiter gerade ausgespielter Rohdiamant? Erhalte 2 Æ." },
    { "id": "ChaosArc", "name": "Chaosbogen", "expansion": "AE", "subtype": "Zauber", "cost": 6, "effect": "Wirken: Füge 3 Schaden zu. +2 Schaden für jeden gebundenen Zauber, der an diesen Riss direkt angrenzt." },
    { "id": "Ignite", "name": "Entzünden", "expansion": "AE", "subtype": "Zauber", "cost": 4, "effect": "Wirken: Füge 2 Schaden zu. Wähle 1 anderen Spieler, der 1 Energie erhält." },
    { "id": "EssenceTheft", "name": "Essenz-Diebstahl", "expansion": "AE", "subtype": "Zauber", "cost": 5, "effect": "Wirken: Füge 3 Schaden zu. Wirfst du jetzt 1 Karte deiner Wahl von der Hand ab? Wähle 1 Spieler, der 1 Leben heilt." },
    { "id": "SearingRuby", "name": "Flammen-Rubin", "expansion": "AE", "subtype": "Kristall", "cost": 4, "effect": "Erhalte 2 Æ. Erhalte 1 Æ, aber nur zum Erwerb von Zaubern." },
    { "id": "FeralLightning", "name": "Blitzsturm", "expansion": "AE", "subtype": "Zauber", "cost": 5, "effect": "Dauerhaft: Darf an einen dunklen Riss gebunden werden (ohne ihn gebündelt zu haben). Wirken: Füge 3 Schaden zu." },
    { "id": "PlanarInsight", "name": "Einblick ins Nichts", "expansion": "AE", "subtype": "Zauber", "cost": 6, "effect": "Wirken: Füge 2 Schaden zu. +1 Schaden für jeden deiner aktiven Risse." },
    { "id": "SpectralEcho", "name": "Spektrales Echo", "expansion": "AE", "subtype": "Zauber", "cost": 3, "effect": "Wirken: Füge 2 Schaden zu. Wähle bis zu 1 Karte auf deiner Hand. Zerstöre sie." },
    { "id": "BurningOpal", "name": "Glühender Opal", "expansion": "AE", "subtype": "Kristall", "cost": 5, "effect": "Erhalte 3 Æ. Wirfst du jetzt 1 Karte deiner Wahl von deiner Hand ab? Wähle 1 anderen Spieler, der 1 Karte zieht." },
    { "id": "ConsumingVoid", "name": "Fressende Leere", "expansion": "AE", "subtype": "Zauber", "cost": 7, "effect": "Wirken: Zerstöre bis zu 2 Karten deiner Wahl auf deiner Hand. Füge X Schaden zu. X = 0/3/6 für 0/1/2 zerstörte Karten." },
    { "id": "UnstablePrism", "name": "Instabiles Prisma", "expansion": "AE", "subtype": "Relic", "cost": 3, "effect": "Spiele 1 Kristall von deiner Hand sofort 2x aus. Dann zerstöre ihn. ODER Erhalte 2 Æ." },
    { "id": "CloudedSapphire", "name": "Getrübter Saphir", "expansion": "AE", "subtype": "Kristall", "cost": 6, "effect": "Erhalte 3 Æ. Ist dies dein genau erster gerade ausgespielter Getrübter Saphir? Wähle 1 anderen Spieler, der 1 Energie erhält." },
    { "id": "MagesTalisman", "name": "Talisman der Magier", "expansion": "AE", "subtype": "Relic", "cost": 5, "effect": "Erhalte 1 Energie. Wähle 1 anderen Spieler, der 1 Energie erhält." },
    { "id": "FlexingDagger", "name": "Gebogener Dolch", "expansion": "AE", "subtype": "Relic", "cost": 2, "effect": "Für den nächsten Riss, den du in deinem Zug bündelst oder aktivierst, zahle 3 Æ weniger. ODER Zerstöre diese Karte und füge 1 Schaden zu." },
    { "id": "LavaTendril", "name": "Lava-Takeln", "expansion": "AE", "subtype": "Zauber", "cost": 4, "effect": "Gebunden: Am Ende von Zauber wirken: Füge 1 Schaden zu. Wirken: Füge 3 Schaden zu." },
    { "id": "BottledVortex", "name": "Vortex in Flaschen", "expansion": "AE", "subtype": "Relic", "cost": 3, "effect": "Wähle bis zu 2 Karten auf deiner Hand/Ablagestapel. Zerstöre sie. Ziehe 1 Karte. Zerstöre Vortex in Flaschen." },
    { "id": "ArcaneNexus", "name": "Arkaner Nexus", "expansion": "AE", "subtype": "Zauber", "cost": 7, "effect": "Gebunden: Du darfst 1 gerade gespielten Kristall zurück auf die Hand nehmen. Wirken: Füge 4 Schaden zu." },
    { "id": "DarkFire", "name": "Dunkles Feuer", "expansion": "AE", "subtype": "Zauber", "cost": 5, "effect": "Wirken: Wirf bis zu 2 Karten deiner Wahl von deiner Hand ab. Füge X Schaden zu. X = 0/3/6 für 0/1/2 abgeworfene Karten." },
    { "id": "PhoenixFlame", "name": "Phoenix-Flamme", "expansion": "AE", "subtype": "Zauber", "cost": 3, "effect": "Wirken: Füge 2 Schaden zu. Wirfst du jetzt 1 Energie ab? +2 Schaden." },
    { "id": "Jade", "name": "Jade", "expansion": "AE", "subtype": "Kristall", "cost": 2, "effect": "Erhalte 2 Æ.", "keywords": ["weak"] },
    { "id": "AmplifyVision", "name": "Erweiterter Blick", "expansion": "AE", "subtype": "Zauber", "cost": 4, "effect": "Wirken: Bündele 1 deiner dunklen Risse mit den geringsten Æ-Kosten. Füge 2 Schaden zu. Sind alle deine Risse aktiv? +1 Schaden." },
    { "id": "BlastingStaff", "name": "Sprengstab", "expansion": "AE", "subtype": "Relic", "cost": 4, "effect": "Wähle 1 Zauber, den du gerade gebunden hat. Wirke ihn und füge +2 Schaden zu." },
    { "id": "SiftersPearl", "name": "Sieber-Perle", "expansion": "AE", "subtype": "Kristall", "cost": 3, "effect": "Erhalte 2 Æ. Du und jeder andere Spieler: Sieh dir die oberste Karte deines Decks an. Du darfst sie abwerfen." },
    { "id": "WildfireWhip", "name": "Feuer-Peitsche", "expansion": "AE", "subtype": "Zauber", "cost": 6, "effect": "Gebunden: In deinem Schritt Aktionen ausführen darfst du 2 Æ bezahlen, um 1 Spieler zu wählen: Wirke 1 seiner gebundenden Zauber. Wirken: Füge 4 Schaden zu." },
    { "id": "FocusingOrb", "name": "Orb der Bündelung", "expansion": "AE", "subtype": "Relic", "cost": 4, "effect": "Bündele 1 Riss deiner Wahl (bei 1 Spieler deiner Wahl). ODER Zerstöre diese Karte und die Feste heilt 3 Leben." },
    { "id": "OblivionSwell", "name": "Bann-Welle", "expansion": "AE", "subtype": "Zauber", "cost": 5, "effect": "Gebunden (1x pro Zug): Erhalte 1 Æ im Schritt Aktionen ausführen. Wirken: Füge 2 Schaden zu. Wirfst du jetzt 1 Kristall ab? +X Schaden. X = Æ-Kosten des Kristalls." },
    { "id": "VoidBond", "name": "Verbindung mit der Leere", "expansion": "Depths", "subtype": "Zauber", "cost": 4, "effect": "Wirken: Füge 3 Schaden zu. Du darfst 1 Spieler wählen und 1 seiner gebundenen Zauber wirken." },
    { "id": "Combustion", "name": "Flammenmeer", "expansion": "Depths", "subtype": "Zauber", "cost": 5, "effect": "Wirken: Füge 1 Monster deiner Wahl 2 Schaden zu. Füge 1 anderem Monster oder dem Erzfeind 2 Schaden zu." },
    { "id": "VimDynamo", "name": "Vim-Generator", "expansion": "Depths", "subtype": "Relic", "cost": 4, "effect": "Erleide 1 Schaden und wähle 1 Spieler, der 2 Karten zieht. ODER Zerstöre diese Karte und wähle 1 Spieler, der 2 Leben heilt und 1 Energie erhält." },
    { "id": "DisintegratingScythe", "name": "Zersetzende Sense", "expansion": "Depths", "subtype": "Zauber", "cost": 7, "effect": "Wirken: Füge 8 Schaden zu. Erleide 1 Schaden. Anstatt diesen Zauber abzuwerfen, zerstöre ihn oder lege ihn auf den Ablagestapel 1 Spielers deiner Wahl." },
    { "id": "MonstrousInferno", "name": "Ungeheures Inferno", "expansion": "Depths", "subtype": "Zauber", "cost": 8, "effect": "Dauerhaft: Dieser Zauber muss auf 2 aneinandergrenzende Risse gebunden werden. Beide Risse sind damit nicht mehr frei. Wirken: Füge 7 Schaden zu. Dieser Schaden ist aufteilbar." },
    { "id": "DevouringShadow", "name": "Verschlingender Schatten", "expansion": "Depths", "subtype": "Zauber", "cost": 6, "effect": "Gebunden: In deinem Schritt Aktionen ausführen wähle 1 Karte auf deiner Hand und zerstöre sie. Wirken: Füge 3 Schaden zu." },
    { "id": "BanishingTopaz", "name": "Topas der Verbannung", "expansion": "Depths", "subtype": "Kristall", "cost": 5, "effect": "Erhalte 2 Æ. Legst du jetzt 1 Karte deiner Wahl von deiner Hand auf dein Deck? Erhalte 2 Æ." },
    { "id": "Transmogrifier", "name": "Verwandler", "expansion": "Depths", "subtype": "Relic", "cost": 4, "effect": "Zerstöre 1 Karte deiner Wahl auf der Hand. Du darfst jetzt 1 Karte gratis erwerben, die bis zu 3 Æ mehr kostet als die zerstörte Karte." },
    { "id": "MoltenHammer", "name": "Flüssig-Hammer", "expansion": "Nameless", "subtype": "Relic", "cost": 5, "effect": "Erhalte 1 Energie. Wähle 1 Spieler. Dieser Spieler darf 1 Karte seiner Wahl auf seiner Hand oder die oberste Karte seines Ablagestapels zerstören." },
    { "id": "Radiance", "name": "Ausstrahlung", "expansion": "Nameless", "subtype": "Zauber", "cost": 8, "effect": "Wirken: Füge 5 Schaden zu. Jeder andere Spieler zieht 1 Karte." },
    { "id": "Blaze", "name": "Feuerbrunst", "expansion": "Nameless", "subtype": "Zauber", "cost": 4, "effect": "Einmalig bei Erwerb: Wähle 1 Spieler und lege diesen Zauber auf seinen Ablagestapel. Wirken: Füge 2 Schaden zu. +1 Schaden für jeden anderen deiner gebundenen und gerade gewirkten Feuersbrunst-Zauber." },
    { "id": "ScryingBolt", "name": "Blitz der Vorsehung", "expansion": "Nameless", "subtype": "Zauber", "cost": 6, "effect": "Wirken: Füge 5 Schaden zu. Wirfst du jetzt 1 Energie ab? Sieh dir die obersten 2 Karten des Erzfeind- Stapels an und lege sie in einer Reihenfolge deiner Wahl zurück." },
    { "id": "SagesBrand", "name": "Mal des Weisen", "expansion": "Nameless", "subtype": "Zauber", "cost": 7, "effect": "Dauerhaft: Dieser Zauber muss auf 2 an einandergrenzende Risse gebunden werden. Beide Risse sind damit nicht mehr frei. Gebunden: Ziehe in deinem Schritt Karten ziehen 1 Karte mehr. Wirken: Füge 6 Schaden zu." },
    { "id": "LeechingAgate", "name": "Blutsauger-Achat", "expansion": "Nameless", "subtype": "Kristall", "cost": 3, "effect": "Einmalig bei Erwerb: Erhalte 1 Energie. Erhalte 2 Æ." },
    { "id": "TemporalHelix", "name": "Zeitspirale", "expansion": "Nameless", "subtype": "Relic", "cost": 7, "effect": "Wähle 1 Spieler und wirke 1 seiner gebundenen Zauber. Der Zauber bleibt gebunden." },
    { "id": "ErraticIngot", "name": "Unreiner Opal", "expansion": "WE", "subtype": "Kristall", "cost": 5, "effect": "Erhalte 2 Æ. Sieh dir den Ablagestapel des Reihenfolgedecks an. Ist dort mindestens 1 Erzfeind-Reihenfolgekarte? Erhalte 2 Æ." },
    { "id": "ReduceToAsh", "name": "Einäschern", "expansion": "WE", "subtype": "Zauber", "cost": 7, "effect": "Gebunden: Zu Beginn von Zauber wirken: Sieh dir die oberste Karte deines Decks an. Du darfst sie zerstören. Wirken: Füge 4 Schaden zu." },
    { "id": "VortexGauntlet", "name": "Vortex-Handschuh", "expansion": "WE", "subtype": "Relic", "cost": 6, "effect": "Wähle 1 Spieler und wirke 1 seiner gebundenen Zauber. Den gewirkten Zauber erhält dieser Spieler zurück auf die Hand (statt auf den Ablagestapel)." },
    { "id": "Carbonize", "name": "Verkohlen", "expansion": "WE", "subtype": "Zauber", "cost": 4, "effect": "Wirken: Füge 3 Schaden zu. Sieh dir die oberste Karte des Reihenfolgedecks an. Du darfst diese Karte unter das Reihenfolgedeck schieben." },
    { "id": "Equilibrium", "name": "Equilibrium", "expansion": "WE", "subtype": "Zauber", "cost": 7, "effect": "Gebunden: Erleidest du Schaden? Reduziere den Schaden um 1 (Minimum: 1 Schaden). Wirken: Füge 4 Schaden zu." },
    { "id": "VolcanicGlass", "name": "Vulkan-Glas", "expansion": "WE", "subtype": "Kristall", "cost": 3, "effect": "Einmalig bei Erwerb: Bezahlst du jetzt 2 Æ? Wähle 1 anderen Spieler, der 1 Vulkan-Glas erhält und oben auf sein Deck legt. Dieser Spieler kann diesen Effekt nicht auslösen. Erhalte 2 Æ." },
    { "id": "ConvectionField", "name": "Konvektions-Feld", "expansion": "WE", "subtype": "Zauber", "cost": 5, "effect": "Wirken: Füge 4 Schaden zu. ODER Wirken: Füge 2 Schaden zu. Wähle 1 anderen Spieler, der 1 Karte seiner Wahl auf der Hand zerstören darf." },
    { "id": "JaggedLightning", "name": "Blitz-Kaskade", "expansion": "WE", "subtype": "Zauber", "cost": 4, "effect": "Wirken: Füge 3 Schaden zu. Wirfst du jetzt 1 Karte deiner Wahl von der Hand ab? Wähle 1 Spieler, der 1 seiner Risse mit den niedrigsten Æ-Kosten bündelt." },
    { "id": "BloodstoneJewel", "name": "Blut-Diamant", "expansion": "WE", "subtype": "Kristall", "cost": 6, "effect": "Einmalig bei Erwerb: Ist dies dein genau erster gerade erworbener Blut-Diamant? Erhalte 3 Æ. Erhalte 3 Æ." },
    { "id": "Kindle", "name": "Entfachen", "expansion": "WE", "subtype": "Zauber", "cost": 4, "effect": "Gebunden: In deinem Schritt Aktionen ausführen darfst du hier auch noch 1 Funken binden (max. 1). Wirken: Füge 3 Schaden zu." },
    { "id": "ThoughtformFamiliar", "name": "Gedankenvertrauter", "expansion": "WE", "subtype": "Zauber", "cost": 3, "effect": "Wirken: Füge 2 Schaden zu. +X Schaden. X = Anzahl deiner anderen gebundenen Zauber." },
    { "id": "Crystallize", "name": "Kristallisieren", "expansion": "WE", "subtype": "Zauber", "cost": 8, "effect": "Dauerhaft: Dieser Zauber muss auf 2 aneinandergrenzende Risse gebunden werden. Beide Risse sind damit nicht mehr frei. Wirken: Füge X Schaden zu. X = 2 für jeden Kristall auf der Hand 1 anderen Spielers deiner Wahl." },
    { "id": "FieryTorrent", "name": "Feuerflut", "expansion": "WE", "subtype": "Zauber", "cost": 5, "effect": "Wirken: Füge 2 Schaden zu. +2 Schaden für jede weitere gebundene Feuerflut im Spiel." },
    { "id": "CelestialSpire", "name": "Himmelsfeuer", "expansion": "WE", "subtype": "Zauber", "cost": 5, "effect": "Wirken: Füge 3 Schaden zu. Ist der Vorrat dieser Karte leer? Wähle 1 anderen Spieler, der 1 Karte von seinem Deck zieht." },
    { "id": "ConjureTheLost", "name": "Rückkehrer beschwören", "expansion": "WE", "subtype": "Zauber", "cost": 6, "effect": "Wirken: Füge 5 Schaden zu. Zerstörst du jetzt diese Karte? Die Feste heilt 4 Leben." },
    { "id": "NovaForge", "name": "Sternenschmiede", "expansion": "WE", "subtype": "Zauber", "cost": 6, "effect": "Gebunden (1x pro Zug): Erhalte 2 Æ im Schritt Aktionen ausführen, aber nur zum Erwerb von Zaubern. Wirken: Füge 4 Schaden zu." },
    { "id": "DreadDiamond", "name": "Terror-Diamant", "expansion": "WE", "subtype": "Kristall", "cost": 3, "effect": "Erhalte 2 Æ. Wirfst du jetzt 1 deiner gebundenen Zauber deiner Wahl ab? Erhalte 1 Æ." },
    { "id": "CairnCompass", "name": "Stein-Kompass", "expansion": "WE", "subtype": "Relic", "cost": 4, "effect": "Wähle 1 anderen Spieler. Dieser Spieler darf 1 Zauber aus seinem Ablagestapel wählen und an seine aktiven oder dunklen Risse binden." },
    { "id": "ScoriaSlag", "name": "Vulkan-Schlacke", "expansion": "WE", "subtype": "Kristall", "cost": 4, "effect": "Erhalte 2 Æ. Ist das Erzfeind-Level 2 oder höher? Erhalte 1 Æ." },
    { "id": "BreachOre", "name": "Riss-Erz", "expansion": "WE", "subtype": "Kristall", "cost": 4, "effect": "Erhalte 2 Æ. ODER Bündele 1 deiner dunklen Risse mit den geringsten Æ-Kosten." },
    { "id": "FiendCatcher", "name": "Teufelschnapper", "expansion": "WE", "subtype": "Relic", "cost": 3, "effect": "Du darfst 1 Karte deiner Wahl auf deiner Hand oder deinem Ablagestapel zerstören. Sieh dir die oberste Karte des Reihenfolgedecks an. Ist es eine Erzfeind-Reihenfolgekarte? Du darfst sie unter das Reihenfolgedeck schieben." },
    { "id": "PyrotechnicSurge", "name": "Pyrotechnische Woge", "expansion": "WE", "subtype": "Zauber", "cost": 4, "effect": "Dauerhaft: Dieser Zauber muss auf 2 aneinandergrenzende Risse gebunden werden. Beide Risse sind damit nicht mehr frei. Wirken: Füge 4 Schaden zu. Du darst 1 Karte deiner Wahl in deinem Ablagestapel zerstören." },
    { "id": "Aurora", "name": "Aurora", "expansion": "WE", "subtype": "Zauber", "cost": 5, "effect": "Gebunden (1x pro Zug): Im Schritt Aktionen ausführen: Erhalte 1 Energie. Wirken: Füge 3 Schaden zu." },
    { "id": "ConclaveScroll", "name": "Kodex der Konklave", "expansion": "WE", "subtype": "Relic", "cost": 3, "effect": "Erhalte 1 Energie. Ist der Vorrat dieser Karte leer? Wähle 1 anderen Spieler, der die oberste Karte seines Ablagestapels zerstören darf." },
    { "id": "PrimordialFetish", "name": "Urzeitlicher Götze", "expansion": "WE", "subtype": "Relic", "cost": 4, "effect": "Bündele 1 Riss deiner Wahl (bei 1 Spieler deiner Wahl). ODER Zerstöre diese Karte und heile 3 Leben." },
    { "id": "FrozenMagmite", "name": "Geforener Magmit", "expansion": "WE", "subtype": "Kristall", "cost": 3, "effect": "Erhalte 2 Æ. Die nächste Karte, die du in deinem Zug erwirbst, darfst du oben auf dein Deck legen." },
    { "id": "MagesTotem", "name": "Magier-Totem", "expansion": "WE", "subtype": "Relic", "cost": 2, "effect": "Wähle und zerstöre 1 Artefakt oder 1 Kristall, den du gerade gespielt hast. ODER Zerstöre diese Karte. Die Feste heilt 1 Leben." },
    { "id": "Char", "name": "Karbonisieren (1. Auflage: Verkohlen)", "expansion": "OD", "subtype": "Zauber", "cost": 8, "effect": "Wirken: Füge 6 Schaden zu. Wird dadurch ein MONSTER getötet? Wähle 1 Spieler, der 2 Leben heilt." },
    { "id": "AlienElement", "name": "Fremdkörper", "expansion": "OD", "subtype": "Kristall", "cost": 4, "effect": "Erhalte 1 Æ. Erhalte 1 Æ für jeden deiner Risse mit einem gebundenen Zauber." },
    { "id": "Scorch", "name": "Versengen", "expansion": "OD", "subtype": "Zauber", "cost": 5, "effect": "Wirken: Füge 4 Schaden zu. Wird dadurch ein MONSTER aus dem Erzfeind-Stapel getötet? Wähle 1 anderen Spieler, der 2 Energie erhält." },
    { "id": "Pyromancy", "name": "Pyromantie", "expansion": "OD", "subtype": "Zauber", "cost": 7, "effect": "Wirken: Füge 1 Schaden zu. Werfen die anderen Spieler jetzt insgesamt bis zu 2 Karten ab? +X Schaden. X = 0/3/6 für 0/1/2 abgeworfene Karten." },
    { "id": "FeedbackAura", "name": "Blitz-Aura", "expansion": "OD", "subtype": "Zauber", "cost": 5, "effect": "Wirken: Füge 3 Schaden zu. Hast du 4 oder mehr Energie? +3 Schaden." },
    { "id": "Catalyst", "name": "Vernichtung", "expansion": "OD", "subtype": "Zauber", "cost": 6, "effect": "Wirken: Füge 2 Schaden zu. Hast du 2 oder weniger übriges Leben? +5 Schaden." },
    { "id": "PainStone", "name": "Schmerzstein", "expansion": "OD", "subtype": "Kristall", "cost": 6, "effect": "Erhalte 3 Æ. ODER Erhalte 2 Æ. Füge 1 Schaden zu." },
    { "id": "AstralCube", "name": "Astral-Würfel", "expansion": "OD", "subtype": "Relic", "cost": 5, "effect": "Hast du gerade 1 Kristall gespielt? Nimm ihn zurück auf deine Hand. Sieh dir die oberste Karte des Reihenfolgedecks an. Siehst du eine Spieler- Reihenfolgekarte? Dieser Spieler heilt 1 Leben." },
    { "id": "RiddleSphere", "name": "Mystische Sphäre", "expansion": "OD", "subtype": "Relic", "cost": 3, "effect": "Erhalte 1 Energie. ODER Wirfst du jetzt 2 Energie ab? Erhalte 5 Æ." },
    { "id": "NetherConduit", "name": "Verbindung zum Nichts", "expansion": "OD", "subtype": "Zauber", "cost": 7, "effect": "Wirken: Wähle 1 Karte auf der Hand mit Æ-Kosten von 2 oder mehr. Füge X Schaden zu. X = Anzahl fehlender Karten im Vorrat dieser Karte. Wähle 1 anderen Spieler, der 1 Karte dieses Vorrats gratis erwerben darf. (Hilfe: Kristall-Vorräte haben 7 Karten. Artefakte und Zauber 5.)" },
    { "id": "HauntedBerylite", "name": "Verfluchter Beryllit", "expansion": "OD", "subtype": "Kristall", "cost": 3, "effect": "Erhalte 2 Æ. ODER Wirf 1 Karte deiner Wahl von der Hand ab. Ist das passiert? Erhalte 2 Energie." },
    { "id": "FossilizedScarab", "name": "Bernstein-Skarabäus", "expansion": "TV", "subtype": "Kristall", "cost": 3, "effect": "Erhalte 2 Æ. ODER Wähle 1 Karte auf deiner Hand und zerstöre sie." },
    { "id": "ThermalDart", "name": "Thermalpfeil", "expansion": "TV", "subtype": "Zauber", "cost": 4, "effect": "Verknüpfbar. (Bis zu 2 verknüpfbare Zauber dürfen gleichzeitig an 1 Riss gebunden sein.) Wirken: Füge 3 Schaden zu. Ist dies dein mindestens 2. gerade gewirkter Thermalpfeil? Erhalte 1 Energie." , "keywords": ["link"] },
    { "id": "Resonate", "name": "Widerhall", "expansion": "TV", "subtype": "Zauber", "cost": 6, "effect": "Wirken: Füge 4 Schaden zu. Sind 6 oder mehr Karten in deinem Ablagestapel? +3 Schaden." },
    { "id": "Conflagration", "name": "Feuersbrunst", "expansion": "TV", "subtype": "Zauber", "cost": 3, "effect": "Verknüpfbar. (Bis zu 2 verknüpfbare Zauber dürfen gleichzeitig an 1 Riss gebunden sein.) Wirken: Füge 2 Schaden zu. Erhalte 1 Æ für Aktionen ausführen." , "keywords": ["link"] },
    { "id": "DimensionalKey", "name": "Dimensions-Schlüssel", "expansion": "TV", "subtype": "Relic", "cost": 8, "effect": "Wähle 1 anderen Spieler, der 2 Karten zieht. ODER Zerstöre diese Karte. Erleide 1 Schaden. Lege 1 Erzfeind-Karte in der Auslage zurück auf den Erzfeind-Stapel." },
    { "id": "InnerFire", "name": "Inneres Feuer", "expansion": "TV", "subtype": "Zauber", "cost": 2, "effect": "Verknüpfbar. (Bis zu 2 verknüpfbare Zauber dürfen gleichzeitig an 1 Riss gebunden sein.) Wirken: Füge 1 Schaden zu. Ist das Erzfeind-Level 2 oder höher? +1 Schaden." , "keywords": ["link"] },
    { "id": "Fulminate", "name": "Feuerstoss", "expansion": "TV", "subtype": "Zauber", "cost": 5, "effect": "Verknüpfbar. (Bis zu 2 verknüpfbare Zauber dürfen gleichzeitig an 1 Riss gebunden sein.) Gebunden: Deine anderen Zauber fügen +1 Schaden zu. Wirken: Füge 3 Schaden zu." , "keywords": ["link"] },
    { "id": "EternityCharm", "name": "Amulett der Ewigkeit", "expansion": "TV", "subtype": "Relic", "cost": 3, "effect": "Bündele 1 deiner dunklen Risse mit den geringsten Æ-Kosten. Sieh dir die 3 obersten Karten deines Decks an. Siehst du Zauber? 1 davon darfst du an deine aktiven/gerade gebündelten Risse binden." },
    { "id": "BranchingRadite", "name": "Verzweigter Radit", "expansion": "Legacy", "subtype": "Kristall", "cost": 4, "effect": "Erhalte 2 Æ. Hast du 2 oder mehr gebundene Zauber? Erhalte 1 Æ." , "keywords": ["weak"] },
    { "id": "FireChakram", "name": "Feuer-Chakra", "expansion": "Legacy", "subtype": "Zauber", "cost": 2, "effect": "Wirken: Füge 2 Schaden zu." , "keywords": ["weak"] },
    { "id": "BraneKnife", "name": "Graviton-Klinge", "expansion": "Legacy", "subtype": "Relic", "cost": 3, "effect": "Erhalte 1 Energie. Wähle 1 anderen Spieler, der seinen dunklen Riss mit den geringsten Æ-Kosten bündelt." , "keywords": ["weak"] },
    { "id": "FulmiteSlab", "name": "Matter Fulmit", "expansion": "Legacy", "subtype": "Kristall", "cost": 6, "effect": "Erhalte 1 Æ. Erhalte 2 Impulse. Bis zum Ende deines Zuges: Wirfst du X Impulse ab? Erhalte X Æ." , "keywords": ["pulse", "strong"] },
    { "id": "GildedMarble", "name": "Vergoldeter Marmor", "expansion": "Legacy", "subtype": "Kristall", "cost": 6, "effect": "Erhalte 3 Æ." , "keywords": ["weak"] },
    { "id": "VoltaicRelay", "name": "Impuls-Stab", "expansion": "Legacy", "subtype": "Relic", "cost": 4, "effect": "Wähle 1 Spieler, der 3 Impulse erhält. Dieser Spieler: Wirfst du jetzt 1 Impuls ab? Zerstöre 1 Karte deiner Wahl auf deiner Hand." , "keywords": ["strong", "pulse"] },
    { "id": "SparkingSiphon", "name": "Heilende Hände", "expansion": "Legacy", "subtype": "Zauber", "cost": 3, "effect": "Einmalig bei Erwerb: Erhalte 2 Impulse. Wirken: Füge 2 Schaden zu. Wirfst du jetzt 1 Impuls ab? Wähle 1 Spieler, der 1 Leben heilt." , "keywords": ["pulse", "strong"] },
    { "id": "BreachCommunion", "name": "Riss-Vereinigung", "expansion": "Legacy", "subtype": "Zauber", "cost": 4, "effect": "Gebunden (1x pro Zug): Erhalte 1 Impuls in deinem Schritt Aktionen ausführen. Wirken: Füge 2 Schaden zu. Wirfst du jetzt 2 Impulse ab? +3 Schaden." , "keywords": ["strong", "pulse"] },
    { "id": "InfernalMirror", "name": "Spiegel des Grauens", "expansion": "Legacy", "subtype": "Relic", "cost": 5, "effect": "Wähle 1 anderen Spieler, der 1 Energie erhält. Wähle 1 Spieler, der 2 Impulse erhält. Wirfst du jetzt 2 Impulse ab? Wähle 1 Spieler und wirke 1 seiner gebundenen Zauber mit +1 Schaden." , "keywords": ["pulse", "strong"] },
    { "id": "Geophage", "name": "Geophage", "expansion": "Legacy", "subtype": "Relic", "cost": 3, "effect": "Erhalte 1 Æ. Du darfst 1 Kristall auf deiner Hand zerstören." , "keywords": ["weak"] },
    { "id": "ForceTransfusion", "name": "Kraft-Transfusion", "expansion": "Legacy", "subtype": "Zauber", "cost": 4, "effect": "Wirken: Füge 3 Schaden zu. Hast du 3 oder mehr Energie? Erhalte 1 Energie." , "keywords": ["weak"] },
    { "id": "ConductiveGrit", "name": "Statischer Sand", "expansion": "Legacy", "subtype": "Kristall", "cost": 3, "effect": "Erhalte 2 Æ. Erhalte 1 Impuls. ODER Wirfst du jetzt 1 Impuls ab? Erhalte 3 Æ." , "keywords": ["pulse", "strong"] },
    { "id": "AncientCyanolith", "name": "Antiker Cyanolit", "expansion": "Legacy", "subtype": "Kristall", "cost": 3, "effect": "Erhalte 2 Æ." , "keywords": ["weak"] },
    { "id": "EtherealHand", "name": "Aetherische Hand", "expansion": "Legacy", "subtype": "Relic", "cost": 6, "effect": "Wähle 1 anderen Spieler, der 2 Karten zieht." , "keywords": ["weak"] },
    { "id": "BendingBeam", "name": "Krümmstrahl", "expansion": "Legacy", "subtype": "Zauber", "cost": 5, "effect": "Wirken: Füge 2 Schaden zu. Ist dieser Zauber an einen aktiven Riss III gebunden? +3 Schaden." , "keywords": ["weak"] },
    { "id": "EntangledShard", "name": "Schwelender Saphir", "expansion": "Legacy", "subtype": "Kristall", "cost": 4, "effect": "Erhalte 2 Æ. Hast du 3 oder mehr Energie? Erhalte 1 Æ." , "keywords": ["weak"] },
    { "id": "ArcaneSalvo", "name": "Arkane Salve", "expansion": "Legacy", "subtype": "Zauber", "cost": 5, "effect": "Gebunden (1x pro Zug): In deinem Schritt Aktionen ausführen darfst du 1 gerade gespieltes Artefakt oder 1 Artefakt in deinem Ablagestapel oben auf dein Deck legen. Wirken: Füge 4 Schaden zu." },
    { "id": "PhasedPortalite", "name": "Gespaltenes Portalit", "expansion": "Legacy", "subtype": "Kristall", "cost": 4, "effect": "Erhalte 2 Æ. Ist dein Riss III aktiv? Erhalte 1 Æ." },
    { "id": "PyroGeist", "name": "Pyro-Phantom", "expansion": "Legacy", "subtype": "Zauber", "cost": 6, "effect": "Einmalig beim Binden: Füge 1 Schaden zu. Wirken: Füge 1 Schaden zu. Füge 2 Schaden zu. (Hinweis: Das sind 2 Schadensquellen.)" },
    { "id": "BreachFlare", "name": "Riss-Feuer", "expansion": "Legacy", "subtype": "Zauber", "cost": 3, "effect": "Wirken: Füge 2 Schaden zu. Bündele 1 Riss III (bei 1 Spieler deiner Wahl)." , "keywords": ["weak"] },
    { "id": "ThunderousOath", "name": "Donnernder Schwur", "expansion": "Legacy", "subtype": "Zauber", "cost": 8, "effect": "Wirken: Füge 6 Schaden zu. Erhalte 1 Impuls. Wirfst du jetzt X Impulse ab? Wähle 1 anderen Spieler, der X Karten zieht." , "keywords": ["pulse", "strong"] },
    { "id": "SoothingTorporene", "name": "Besänftiger Petalit", "expansion": "Legacy", "subtype": "Kristall", "cost": 3, "effect": "Erhalte 2 Æ. ODER Betäube 1 MONSTER deiner Wahl." , "keywords": ["silence"] },
    { "id": "ArcingSilicate", "name": "Funkenschlag-Silikat", "expansion": "Legacy", "subtype": "Kristall", "cost": 4, "effect": "Erhalte 2 Æ. Erhalte 1 Impuls. Wirfst du jetzt X Impulse ab? Füge X Schaden zu." , "keywords": ["pulse", "strong"] },
    { "id": "WarpingHaze", "name": "Zeiten-Schleier", "expansion": "Legacy", "subtype": "Zauber", "cost": 3, "effect": "Wirken: Füge 2 Schaden zu. Hast du 2 oder mehr weitere gebundene Zauber? +1 Schaden." , "keywords": ["weak"] },
    { "id": "IncineratingFist", "name": "Flammenfaust", "expansion": "Legacy", "subtype": "Zauber", "cost": 4, "effect": "Wirken: Füge 3 Schaden zu." , "keywords": ["weak"] },
    { "id": "RealityStabilizer", "name": "Gefäss der Erkenntnis", "expansion": "Legacy", "subtype": "Relic", "cost": 6, "effect": "Erhalte 2 Energie. Betäube 1 MONSTER deiner Wahl." , "keywords": ["silence"] },
    { "id": "BreachCollision", "name": "Riss-Kollision", "expansion": "Legacy", "subtype": "Zauber", "cost": 7, "effect": "Einmalig bei Erwerb: Du darfst diese Karte auf einen Ablagestapel deiner Wahl legen. Wirken: Füge 5 Schaden zu. Die Feste heilt 1 Leben." },
    { "id": "FieryConclusion", "name": "Feuerwirbel", "expansion": "Legacy", "subtype": "Zauber", "cost": 5, "effect": "Wirken: Füge 4 Schaden zu. 3 oder mehr leere Vorräte? +3 Schaden." , "keywords": ["strong"] },
    { "id": "StarfireFrenzy", "name": "Sternenfeuer-Raserei", "expansion": "Legacy", "subtype": "Zauber", "cost": 6, "effect": "Wirken: Füge 4 Schaden zu. Wirfst du jetzt 1 Zauber deiner Hand ab? +1 Schaden und erhalte 1 Energie." , "keywords": ["weak"] },
    { "id": "CrumblingCompound", "name": "Antimonit-Brocken", "expansion": "Legacy", "subtype": "Kristall", "cost": 5, "effect": "Erhalte 2 Æ. Wirfst du jetzt 1 Kristall von deiner Hand ab? Erhalte 2 Æ." , "keywords": ["weak"] },
    { "id": "PropheticLens", "name": "Linse der Prophezeiung", "expansion": "Legacy", "subtype": "Relic", "cost": 4, "effect": "Erhalte 1 Energie. Sieh dir die oberste Karte deines Decks an. Du darfst sie zerstören. Tust du das nicht? Erhalte 1 Æ." , "keywords": ["strong"] },
    { "id": "AdrenalBatteries", "name": "Energieladung", "expansion": "Legacy", "subtype": "Relic", "cost": 7, "effect": "Erhalte 2 Impulse. Wirfst du jetzt 4 Impulse ab? Aktiviere 1 dunklen Riss bei 1 Spieler deiner Wahl. Erwirb gratis 1 Zauber deiner Wahl mit Æ-Kosten von 5 oder weniger. Binde diesen Zauber an 1 aktiven Riss bei 1 Spieler deiner Wahl." , "keywords": ["pulse", "strong"] },
    { "id": "RefinedLumenium", "name": "Veredeltes Lumenium", "expansion": "Legacy", "subtype": "Kristall", "cost": 5, "effect": "Erhalte 2 Æ. Wähle 1 anderen Spieler, der 1 Karte zieht." },
    { "id": "VoidMill", "name": "Steuerrad der Leere", "expansion": "Legacy", "subtype": "Relic", "cost": 5, "effect": "Bündele 1 Riss deiner Wahl (bei 1 Spieler deiner Wahl). Wähle 2 Spieler. Diese Spieler dürfen die oberste Karte ihres Ablagestapels zerstören." },
    { "id": "GravityNode", "name": "Gravitations-Knoten", "expansion": "Legacy", "subtype": "Zauber", "cost": 5, "effect": "Wirken: Wähle 1 Spieler, der 1 Karte seiner Wahl von der Hand abwirft. Ist das passiert? Füge 4 Schaden zu." , "keywords": ["weak"] },
    { "id": "NeuralWreath", "name": "Neuronen-Kranz", "expansion": "Legacy", "subtype": "Relic", "cost": 4, "effect": "Bündele 1 Riss deiner Wahl (bei 1 Spieler deiner Wahl). Wähle 1 Spieler. Dieser Spieler darf 1 Zauber seiner Wahl von der Hand an seine aktiven / gerade gebündelten Risse binden." , "keywords": ["weak"] },
    { "id": "SphereOfInversion", "name": "Inversionssphäre", "expansion": "Legacy", "subtype": "Zauber", "cost": 9, "effect": "Wirken: Füge 7 Schaden zu. Zerstört 1 anderer Spieler 1 Karte seiner Wahl auf der Hand? Dieser Spieler heilt 2 Leben." , "keywords": ["strong"] },
    { "id": "LurkingSionite", "name": "Unscheinbarer Sionit", "expansion": "NA", "subtype": "Kristall", "cost": 3, "effect": "Erhalte 2 Æ. Befindet sich mindestens 1 Unscheinbarer Sionit im Ablagestapel eines anderen Spielers? Erhalte 1 Æ." },
    { "id": "UnrefinedBlaststone", "name": "Unreiner Sprengstein", "expansion": "NA", "subtype": "Kristall", "cost": 6, "effect": "Erhalte 3 Æ. OR Zerstörst du jetzt 1 Karte dieses Vorrats? Füge 3 Schaden zu." },
    { "id": "Exogranite", "name": "Exogranit", "expansion": "NA", "subtype": "Kristall", "cost": 3, "effect": "Erhalte 2 Æ OR Zerstöre diese Karte. Erhalte 3 Æ." },
    { "id": "RecurringJasper", "name": "Wiederkehrender Jaspis", "expansion": "NA", "subtype": "Kristall", "cost": 4, "effect": "Erhalte 2 Æ. Ist die oberste Karte deines Ablagestapels ein Zauber? Du darfst diesen Kristall oben auf dein Deck legen." },
    { "id": "EnergizedRubidium", "name": "Aufgeladenes Rubidium", "expansion": "NA", "subtype": "Kristall", "cost": 5, "effect": "Erhalte 3 Æ. Wirft 1 anderer Spieler 1 Karte seiner Wahl von der Hand ab? Dieser Spieler erhält 1 Energie." },
    { "id": "ResonantPearl", "name": "Resonanzperle", "expansion": "NA", "subtype": "Kristall", "cost": 3, "effect": "Erhalte 2 Æ. Wirft 1 anderer Spieler eine Resonanzperle von der Hand ab und zieht 1 Karte? Erhalte 1 Æ." },
    { "id": "CagedFire", "name": "Gebändigtes Feuer", "expansion": "NA", "subtype": "Relic", "cost": 3, "effect": "Wähle 1 Spieler und zerstöre die oberste Karte seines Ablagestapels. OR Zerstöre diese Karte. Heile 2 Leben." },
    { "id": "GalvanizedBauble", "name": "Galvanisierter Polyeder", "expansion": "NA", "subtype": "Relic", "cost": 3, "effect": "Wähle 1 anderen Spieler und bündele 1 seiner Risse deiner Wahl. OR Wähle 1 Spieler und wirke 1 seiner gebundenen Zauber. Du darfst diesen Zauber zerstören." },
    { "id": "AetherConduit", "name": "Ätherkanal", "expansion": "NA", "subtype": "Relic", "cost": 4, "effect": "Hänge diese Karte an 1 Riss deiner Wahl an (bei einem Spieler deiner Wahl). Angehängt: Wird ein Zauber von diesem Riss gewirkt? Der Spieler, der den Zauber gewirkt hat, erhält 1 Æ." , "keywords": ["attach"] },
    { "id": "WellOfEnergy", "name": "Wohltuende Quelle", "expansion": "NA", "subtype": "Relic", "cost": 7, "effect": "Die Feste heilt 2 Leben. OR Wähle 1 Spieler, der 2 Leben heilt." },
    { "id": "PainConduit", "name": "Schmerzkanal", "expansion": "NA", "subtype": "Relic", "cost": 3, "effect": "Hänge diese Karte an einen Riss deiner Wahl an (bei 1 Spieler deiner Wahl). Angehängt: Wird ein Zauber von diesem Riss gewirkt? +2 Schaden. Wirf diese Karte danach ab." , "keywords": ["attach"] },
    { "id": "LinkConduit", "name": "Verkettungskanal", "expansion": "NA", "subtype": "Relic", "cost": 6, "effect": "Hänge diese Karte an 1 Riss deiner Wahl an (bei einem Spieler deiner Wahl). Angehängt: An diesen Riss dürfen 2 Zauber gleichzeitig gebunden sein." , "keywords": ["attach"] },
    { "id": "MarbleGalaxy", "name": "Galaxiekugel", "expansion": "NA", "subtype": "Relic", "cost": 2, "effect": "Erhalte 1 Energie. OR Bündele 1 deiner dunklen Risse. Wirft 1 anderer Spieler 1 Galaxiekugel von der Hand ab und zieht 1 Karte? Führe zusätzlich den obigen, gerade nicht gewählten Effekt dieser Karte aus." },
    { "id": "DelugeOfPower", "name": "Reinigende Flut", "expansion": "NA", "subtype": "Zauber", "cost": 6, "effect": "Wirken: Füge 4 Schaden zu. Wähle 1 anderen Spieler. Dieser Spieler darf bis zu 2 Karten seiner Wahl von der Hand abwerfen und dann 1 Karte für jede so abgeworfene Karte ziehen." },
    { "id": "ReverberatingShock", "name": "Nachhallender Schock", "expansion": "NA", "subtype": "Zauber", "cost": 4, "effect": "ECHO. Wirken: Füge 1 Schaden zu. Erhalte 1 Æ, aber nur zum Erwerb von Karten." , "keywords": ["echo"] },
    { "id": "FatalHarmony", "name": "Fatale Harmonie", "expansion": "NA", "subtype": "Zauber", "cost": 5, "effect": "Wirken: Füge 4 Schaden zu. Wirft 1 anderer Spieler Fatale Harmonie von seiner Hand ab und zieht 1 Karte? Füge 3 Schaden zu. (Hinweis: Das sind 2 Schadensquellen.)" },
    { "id": "BouncingBoom", "name": "Springendes Geschoss", "expansion": "NA", "subtype": "Zauber", "cost": 6, "effect": "ECHO. Wirken: Füge 2 Schaden zu." , "keywords": ["echo"] },
    { "id": "SpiritLift", "name": "Machtschub", "expansion": "NA", "subtype": "Zauber", "cost": 8, "effect": "Gebunden (1x pro Zug): Erhältst du 1 Energie? Wähle 1 anderen Spieler, der 2 Energie erhält. Wirken: Füge 5 Schaden zu." },
    { "id": "Tethered Darts", "name": "Lenk-Pfeile", "expansion": "NA", "subtype": "Zauber", "cost": 3, "effect": "Wiken: Füge 2 Schaden zu. Ist dieser Zauber an einen aktiven Riss III oder IV gebunden? Wähle 1 anderen Spieler. Dieser Spieler darf diesen Zauber auf die Hand nehmen." },
    { "id": "ForceAmplifier", "name": "Kraftverstärker", "expansion": "NA", "subtype": "Zauber", "cost": 4, "effect": "Wirken: Füge 3 Schaden zu. Ist dieser Zauber an einen aktiven Riss III oder IV gebunden? +1 Schaden." },
    { "id": "ImbuedSmash", "name": "Geballte Ladung", "expansion": "NA", "subtype": "Zauber", "cost": 5, "effect": "Wirken: Füge 4 Schaden zu. Wirfst du jetzt 1 Karte von der Hand ab? Füge dem Erzfeind 2 Schaden zu. (Hinweis: Das sind 2 Schadensquellen.)" },
    { "id": "PatternStrike", "name": "Schematischer Schlag", "expansion": "NA", "subtype": "Zauber", "cost": 7, "effect": "Wirken: Füge 4 Schaden zu. Du darfst bis zu 2 Karten mit Æ-Kosten von 0 aus deinem Ablagestapel zurück auf die Hand nehmen." },
    { "id": "ShiningFluorite", "name": "Schimmernder Fluorit", "expansion": "TA", "subtype": "Kristall", "cost": 7, "effect": "Erhalte 3 Æ. Nimm den nächsten Zauber, den du in diesem Zug erwirbst, direkt auf deine Hand." },
    { "id": "PolyphaseTurbine", "name": "Polyphasen-Turbine", "expansion": "TA", "subtype": "Relic", "cost": 3, "effect": "Ist das die erste Polyphasen-Turbine, die du in diesem Zug gespielt hast? Erhalte 2 Æ. Andernfalls: Erhalte 1 Æ und 1 Energie." },
    { "id": "BreachExtractor", "name": "Riss-Greifer", "expansion": "TA", "subtype": "Relic", "cost": 5, "effect": "Wähle 1 Spieler, der bis zu 2 Karten auf seiner Hand zerstört. OR Zerstöre diese Karte. Die Feste heilt 3 Leben." },
    { "id": "FocusingConduit", "name": "Bündelungskanal", "expansion": "TA", "subtype": "Relic", "cost": 5, "effect": "Hänge diese Karte an 1 Riss deiner Wahl an (bei 1 Spieler deiner Wahl). Angehängt: Bündele diesen Riss nach deinem Schritt Zauber wirken. Zerstöre diese Karte, sobald der Riss aktiviert wird." },
    { "id": "DualFlash", "name": "Doppelschlag", "expansion": "TA", "subtype": "Zauber", "cost": 3, "effect": "Wirken: Füge 2 Schaden zu. Ist das der erste Doppelschlag, den du in diesem Schritt Zauber wirken in diesem Zug gewirkt hast? Du darfst 1 gebundenen Doppelschlag (von 1 Spieler deiner Wahl) wirken, der gebunden bleibt." },
    { "id": "DustCaller", "name": "Wirbel der Wiederkehr", "expansion": "TA", "subtype": "Zauber", "cost": 5, "effect": "Wirken: Füge 4 Schaden zu. Wähle 1 anderen Spieler. Dieser Spieler nimmt 1 Karte mit Æ-Kosten von 0 aus seinem Ablagestapel zurück auf die Hand." },
    { "id": "SymbioticSynapse", "name": "Symbiotische Synthese", "expansion": "TA", "subtype": "Zauber", "cost": 7, "effect": "Wirken: Füge 4 Schaden zu. Befindet sich mindestens 1 weitere Karte Symbiotische Synthese in einem Spieler-Ablagestapel? ECHO." , "keywords": ["echo"] },
    { "id": "JeweledBrain", "name": "Juwelen-Cerebrum", "expansion": "IW", "subtype": "Kristall", "cost": 3, "effect": "Erhalte 2 Æ. OR Erhalte 1 Æ. Wähle 1 Karte in deinem Ablagestapel mit Æ-Kosten von 0 und nimm sie zurück auf die Hand." },
    { "id": "BlastSphere", "name": "Sprengkugel", "expansion": "IW", "subtype": "Relic", "cost": 8, "effect": "Wähle 1 Spieler und wirke 1 seiner gebundenen Zauber 3-mal, ohne ihn abzuwerfen. Dann zerstöre den gewirkten Zauber." },
    { "id": "WoundMender", "name": "Wunderheilung", "expansion": "IW", "subtype": "Zauber", "cost": 8, "effect": "ECHO. Wirken: Füge 2 Schaden zu. Ist dieser Zauber an einen aktiven Riss III oder IV gebunden? Heile 1 Leben." , "keywords": ["echo"] },
    { "id": "Olivinite", "name": "Olivinit", "expansion": "SD", "subtype": "Kristall", "cost": 3, "effect": "Erhalte 2 Æ. OR Füge 1 MONSTER deiner Wahl 1 Schaden zu." },
    { "id": "CacheGlass", "name": "Spektral-Glas", "expansion": "SD", "subtype": "Kristall", "cost": 4, "effect": "Erhalte 2 Æ. Befindet sich mindestens 1 Spektral-Glas in deinem Ablagestapel? Du darfst 1 Karte deiner Wahl in deinem Ablagestapel zerstören." },
    { "id": "ReflectiveConduit", "name": "Reflexionskanal", "expansion": "SD", "subtype": "Relic", "cost": 3, "effect": "Hänge diese Karte an 1 Riss deiner Wahl an (bei 1 Spieler deiner Wahl). Angehängt: Wird ein Zauber von diesem Riss gewirkt? Der Spieler, der den Zauber gewirkt hat, darf ihn zurück auf die Hand nehmen (statt auf den Ablagestapel). Tut er das? Wirf diese Karte ab." , "keywords": ["attach"] },
    { "id": "WillWeaver", "name": "Willensfessel", "expansion": "SD", "subtype": "Relic", "cost": 7, "effect": "Erhalte 2 Energie. Nachdem du das nächste Mal in diesem Zug deine Spezialfähigkeit eingesetzt hast: Füge 3 Schaden zu." },
    { "id": "BreachSeeker", "name": "Riss-Suche", "expansion": "SD", "subtype": "Zauber", "cost": 5, "effect": "ECHO. Wirken: Füge 1 Schaden zu. Wähle 1 anderen Spieler und bündele 1 seiner Risse deiner Wahl." , "keywords": ["echo"] },
    { "id": "CrescendoRay", "name": "Crescendo-Strahl", "expansion": "SD", "subtype": "Zauber", "cost": 4, "effect": "Wirken: Füge 3 Schaden zu. Erhalte 1 Æ für jeden weiteren deiner gebundenen Zauber." },
    { "id": "StormVapors", "name": "Sturm-Schwaden", "expansion": "SD", "subtype": "Zauber", "cost": 4, "effect": "Wirken: Füge 3 Schaden zu. Befindet sich mindestens 1 weitere Karte Sturm-Schwaden in deinem Spieler-Ablagestapel? Bündele 1 Riss deiner Wahl (bei 1 Spieler deiner Wahl)." },
    { "id": "MantraOfStrength", "name": "Mantra der Stärke", "expansion": "SD", "subtype": "Zauber", "cost": 3, "effect": "Wirken: Wähle 1 Spieler, der 1 seiner dunklen Risse mit den höchsten Æ-Kosten bündelt. Füge 1 Schaden zu. Zerstörst du jetzt diese Karte? +2 Schaden." },
    { "id": "EmbodyFlame", "name": "Flammenkette", "expansion": "SD", "subtype": "Zauber", "cost": 7, "effect": "Wirken: Füge 5 Schaden zu. Zerstörst du jetzt 1 Karte dieses Vorrats? +3 Schaden." },
    { "id": "SnapRitual", "name": "Kristall Ritual", "expansion": "SD", "subtype": "Zauber", "cost": 6, "effect": "Gebunden (1x pro Zug): Wirfst du in deinem Schritt Aktionen ausführen 1 Karte deiner Wahl von der Hand ab? Füge 2 Schaden zu. Wirken: Füge 3 Schaden zu." },
    { "id": "DrownInFlames", "name": "In Flammen ertrinken", "expansion": "promos", "subtype": "Zauber", "cost": 6, "effect": "Wirken: Füge 4 Schaden zu. Wiederhole das, wenn du 2 Energie abwirfst.", "disabled": true },
    { "id": "FleetingVision", "name": "Flüchtiger Blick", "expansion": "promos", "subtype": "Zauber", "cost": 3, "effect": "Wirken: Füge 2 Schaden zu. Jeder Spieler: Sieh dir die 2 obersten Karten deines Decks an. Du darfst sie jeweils abwerfen.", "disabled": true },
    { "id": "SplinterMissile", "name": "Splitter-Geschoss", "expansion": "promos", "subtype": "Zauber", "cost": 5, "effect": "Wirken: Füge 4 Schaden zu. Wirft 1 anderer Spieler deiner Wahl 1 Karte von seiner Hand ab? Der Schaden ist nun aufteilbar.", "disabled": true },
    { "id": "EchoStone", "name": "Resonanz-Stein", "expansion": "promos", "subtype": "Kristall", "cost": 4, "effect": "Erhalte 2 Æ. Ist dies dein mindestens zweiter gerade gespielter Resonanz-Stein? Erhalte 1 Æ.", "disabled": true },
    { "id": "ThievingSpirit", "name": "Diebischer Wichtel", "expansion": "promos", "subtype": "Zauber", "cost": 5, "effect": "Wirken: Füge 4 Schaden zu. Erhalte 1 Æ.", "disabled": true },
    { "id": "FracturedQuartz", "name": "Gesplitterter Quarz", "expansion": "promos", "subtype": "Kristall", "cost": 4, "effect": "Erhalte 2Æ. Zerstörst du jetzt 2 Karten dieses Vorrats? Erhalte 1 Æ." },
    { "id": "RockLauncher", "name": "Kristallwerfer", "expansion": "promos", "subtype": "Relic", "cost": 3, "effect": "Wähle 1 Karte von deiner Hand. Wirf sie ab ODER zerstöre sie. Ist das passiert? Füge X Schaden zu.\nX= Kosten der abgeworfenen/zerstörten Karte." },
    { "id": "AbacusOfIgnition", "name": "Flammakus", "expansion": "promos", "subtype": "Relic", "cost": 4, "effect": "Wähle 1 anderen Spieler. Du darfst 1 seiner gebundenen Zauber wirken.\nWähle erneut 1 anderen Spieler, der 1 Karte zieht. (Du darfst bei beiden Effekten denselben Spieler wählen.)" },
    { "id": "IlluminatingFlame", "name": "Erleuchtende Flamme", "expansion": "promos", "subtype": "Zauber", "cost": 6, "effect": "WIRKEN: Füge 5 Schaden zu. Ist der Zauber an einen aktiven Riss III oder IV gebunden? Du darfst diesen Zauber zerstören. Tust du das? Erhalte 3 Energie." },
    { "id": "ChronalArc", "name": "Zeitbogen", "expansion": "promos", "subtype": "Zauber", "cost": 7, "effect": "DAUERHAFT: Dieser Zauber muss auf 2 aneinandergrenzende Risse gebunden werden.\nWIRKEN: Füge 4 Schaden zu. Du darfst diesen Zauber zurück auf die Hand nehmen." },
    { "id": "CoruscatingSapal", "name": "Coruscating Sapal", "expansion": "promos", "subtype": "Kristall", "cost": 4, "effect": "Gain 2 Æ. You may lose 1 charge. If you do, gain an additional 2 Æ.", "disabled": true },
    { "id": "HummingShell", "name": "Humming Shell", "expansion": "promos", "subtype": "Relic", "cost": 7, "effect": "Destroy up to two cards in hand or discard pile. OR Gain 2 charges.", "disabled": true },
    { "id": "ForceCatalyst", "name": "Force Catalyst", "expansion": "promos", "subtype": "Zauber", "cost": 4, "effect": "While prepped, during you main phase you may spend 3 Æ to cast any player's prepped spell. Cast: Deal 3 damage.", "disabled": true },
  ],
  // Vordefinierte Marktplatz-Setups, 1:1 aus dem Original-Randomizer übernommen:
  // aeons-end-randomizer-main/src/aer-data/src/marketSetups.ts (Objekt MARKETSETUPS).
  // Jedes Setup besteht aus genau 9 "Tiles" (Constraint-Slots), die im Original in der
  // Reihenfolge Kristall(Gem)/Relic/Zauber(Spell) definiert sind — NICHT wie im
  // Screenshot der Original-App farblich links->rechts "Spell/Gem/Relic" gruppiert. Die
  // tatsächliche Farbzuordnung laut Original-Theme (src/mainTheme.ts, colors.cards):
  //   Kristall (Gem)   -> Violett  (#EDE7F6 / #B39DDB)
  //   Relic (FE: Artefakt) -> Blau     (#E3F2FD / #90CAF9)
  //   Zauber   (Spell) -> Beige/Gold (#FFF3E0 / #FFCC80)
  // op: '<' | '>' | '<=' | '>=' | '=' | 'OR' | 'ANY' (siehe filterByCost() im Original,
  // src/Redux/helpers.ts). Bei 'OR' gilt threshold=values[]. "hidden: true" markiert das
  // Setup "random", das im Original als Default-Fallback dient und NICHT in den Optionen
  // als Checkbox auftaucht (im Original: das "default"-Flag entfernt es aus den Settings).
  "marketSetups": [
    {
      "id": "market1inc",
      "name": "Marktplatz-Setup 1 (inklusiv)",
      "tiles": [
        { "subtype": "Kristall", "op": "<", "threshold": 4 },
        { "subtype": "Kristall", "op": "=", "threshold": 4 },
        { "subtype": "Kristall", "op": "ANY" },
        { "subtype": "Relic", "op": "ANY" },
        { "subtype": "Relic", "op": "ANY" },
        { "subtype": "Zauber", "op": "<=", "threshold": 5 },
        { "subtype": "Zauber", "op": "<=", "threshold": 5 },
        { "subtype": "Zauber", "op": ">=", "threshold": 5 },
        { "subtype": "Zauber", "op": ">=", "threshold": 5 }
      ]
    },
    {
      "id": "market1",
      "name": "Marktplatz-Setup 1",
      "tiles": [
        { "subtype": "Kristall", "op": "<", "threshold": 4 },
        { "subtype": "Kristall", "op": "=", "threshold": 4 },
        { "subtype": "Kristall", "op": "ANY" },
        { "subtype": "Relic", "op": "ANY" },
        { "subtype": "Relic", "op": "ANY" },
        { "subtype": "Zauber", "op": "<", "threshold": 5 },
        { "subtype": "Zauber", "op": "<", "threshold": 5 },
        { "subtype": "Zauber", "op": ">", "threshold": 5 },
        { "subtype": "Zauber", "op": ">", "threshold": 5 }
      ]
    },
    {
      "id": "market2",
      "name": "Marktplatz-Setup 2",
      "tiles": [
        { "subtype": "Kristall", "op": "<", "threshold": 3 },
        { "subtype": "Kristall", "op": ">", "threshold": 3 },
        { "subtype": "Kristall", "op": ">", "threshold": 3 },
        { "subtype": "Relic", "op": ">", "threshold": 4 },
        { "subtype": "Relic", "op": "ANY" },
        { "subtype": "Zauber", "op": "<", "threshold": 6 },
        { "subtype": "Zauber", "op": "<", "threshold": 6 },
        { "subtype": "Zauber", "op": "<", "threshold": 6 },
        { "subtype": "Zauber", "op": ">", "threshold": 6 }
      ]
    },
    {
      "id": "market3",
      "name": "Marktplatz-Setup 3",
      "tiles": [
        { "subtype": "Kristall", "op": "<", "threshold": 4 },
        { "subtype": "Kristall", "op": "OR", "values": [4, 5] },
        { "subtype": "Kristall", "op": "OR", "values": [4, 5] },
        { "subtype": "Relic", "op": "ANY" },
        { "subtype": "Zauber", "op": "=", "threshold": 3 },
        { "subtype": "Zauber", "op": "=", "threshold": 4 },
        { "subtype": "Zauber", "op": ">", "threshold": 5 },
        { "subtype": "Zauber", "op": ">", "threshold": 5 },
        { "subtype": "Zauber", "op": ">", "threshold": 5 }
      ]
    },
    {
      "id": "market4",
      "name": "Marktplatz-Setup 4",
      "tiles": [
        { "subtype": "Kristall", "op": ">", "threshold": 4 },
        { "subtype": "Kristall", "op": "ANY" },
        { "subtype": "Kristall", "op": "ANY" },
        { "subtype": "Relic", "op": "<", "threshold": 4 },
        { "subtype": "Relic", "op": ">", "threshold": 4 },
        { "subtype": "Relic", "op": "ANY" },
        { "subtype": "Zauber", "op": "<", "threshold": 5 },
        { "subtype": "Zauber", "op": ">", "threshold": 5 },
        { "subtype": "Zauber", "op": "ANY" }
      ]
    },
    {
      "id": "market5",
      "name": "Marktplatz-Setup 5",
      "tiles": [
        { "subtype": "Kristall", "op": "=", "threshold": 2 },
        { "subtype": "Kristall", "op": "=", "threshold": 3 },
        { "subtype": "Kristall", "op": "=", "threshold": 4 },
        { "subtype": "Kristall", "op": "=", "threshold": 5 },
        { "subtype": "Relic", "op": "ANY" },
        { "subtype": "Zauber", "op": "=", "threshold": 4 },
        { "subtype": "Zauber", "op": "=", "threshold": 5 },
        { "subtype": "Zauber", "op": "=", "threshold": 6 },
        { "subtype": "Zauber", "op": ">", "threshold": 6 }
      ]
    },
    {
      "id": "market6",
      "name": "Marktplatz-Setup 6",
      "tiles": [
        { "subtype": "Kristall", "op": "=", "threshold": 3 },
        { "subtype": "Kristall", "op": "=", "threshold": 4 },
        { "subtype": "Relic", "op": "<", "threshold": 4 },
        { "subtype": "Relic", "op": ">", "threshold": 4 },
        { "subtype": "Relic", "op": "ANY" },
        { "subtype": "Zauber", "op": "OR", "values": [3, 4] },
        { "subtype": "Zauber", "op": "OR", "values": [5, 6] },
        { "subtype": "Zauber", "op": "OR", "values": [5, 6] },
        { "subtype": "Zauber", "op": ">", "threshold": 6 }
      ]
    },
    {
      "id": "random",
      "name": "Zufalls-Setup (Standard)",
      "hidden": true,
      "tiles": [
        { "subtype": "Kristall", "op": "ANY" },
        { "subtype": "Kristall", "op": "ANY" },
        { "subtype": "Kristall", "op": "ANY" },
        { "subtype": "Relic", "op": "ANY" },
        { "subtype": "Relic", "op": "ANY" },
        { "subtype": "Zauber", "op": "ANY" },
        { "subtype": "Zauber", "op": "ANY" },
        { "subtype": "Zauber", "op": "ANY" },
        { "subtype": "Zauber", "op": "ANY" }
      ]
    }
  ],

  // Kurzer, einzigartiger Niederlage-Flavortext je Erzfeind — wird auf dem Screen
  // "Niederlage — Belohnung wählen" unter der Überschrift angezeigt, sobald die Feste
  // der Letzten Ruhe auf 0 Trefferpunkte gefallen ist.
  "nemesisDefeatTexts": {
    "CarapaceQueen": "Die Carapax-Königin durchbricht die Mauern — ihr Panzer saugt die letzten Funken auf, bevor die Feste standhalten kann.",
    "CrookedMask": "Der König der Masken lächelt aus tausend Gesichtern, während die letzten Verteidiger ihre eigenen Schritte nicht mehr wiedererkennen.",
    "PrinceOfGluttons": "Der Unersättliche verschlingt die letzte Verteidigungslinie, als wäre sie nur ein weiterer Bissen.",
    "Rageborne": "Hassgeburt tobt durch die Gassen der Feste, bis nur noch Trümmer und Schweigen bleiben.",
    "Necroswarm": "Der Nekroschwarm legt sich wie ein zweiter Himmel über die Feste — und darunter erlischt jedes Licht.",
    "Bladius": "Bladius' Klingen tanzen durch die letzten Reihen, ruhig, unaufhaltsam, ohne ein einziges überflüssiges Wort.",
    "Deathmind": "Der Gedankenschlächter flüstert in jeden Kopf zugleich — und die Verteidiger vergessen, wofür sie kämpften.",
    "FungalMesh": "Der Grosse Todling breitet sein Geflecht über die Feste, bis Stein und Wille gleichermaßen weich werden.",
    "MaelstromRisen": "Der Wiederkehrer reißt die Feste zurück in einen Strudel, den man längst überwunden glaubte.",
    "SpawningHorror": "Der Brutegel lässt seine Brut durch jede Ritze der Feste quellen, schneller als sie sich schließen lassen.",
    "XaxosAscended": "Xaxos, entfesselt, zerreißt die Risse selbst — und die Feste hat keinen Boden mehr, auf dem sie stehen kann.",
    "HazeFiend": "Der Herr der Schleier lässt die Feste im Nebel verschwinden, bevor jemand sieht, woher der nächste Schlag kommt.",
    "ThriceDeadProphet": "Der Dreimaltote Prophet verkündet das Ende der Feste ein drittes Mal — und dieses Mal behält er recht.",
    "Wraithmonger": "Der Traum-Händler bietet der Feste einen letzten Handel an, den niemand mehr ablehnen kann.",
    "TheWailing": "Donnerkreisch übertönt jeden Befehl, jedes Signal, bis die Verteidigung nur noch aus Lärm und Chaos besteht.",
    "TheWanderer": "Der Wanderer betritt die Feste, als wäre sie schon lange sein Ziel gewesen — und verlässt sie als Sieger.",
    "HordeCrone": "Die Horden-Muhme treibt ihre Schar durch die letzten Gassen, bis nichts mehr steht, das sich verteidigen ließe.",
    "BlightLord": "Der Lord des Verderbens lässt die Feste von innen verfaulen, lange bevor die letzte Mauer fällt.",
    "WaywardOne": "Der Wegbereiter öffnet einen Pfad, den die Feste nicht schließen kann — und was ihm folgt, lässt sich nicht aufhalten.",
    "Maggoth": "Madrox windet sich durch jede Verteidigungslinie, geduldig, unaufhaltsam, bis die Feste erschöpft nachgibt.",
    "Arachnos": "Arachnos webt sein Netz über die Feste, Faden für Faden, bis sich niemand mehr rühren kann.",
    "AgelessWalker": "Der Ewigtote geht weiter, wo jeder andere längst gefallen wäre — und die Feste fällt zuerst.",
    "Fenrix": "Fenrix hetzt durch die Straßen der Feste, schneller als jede Warnung sie erreichen kann.",
    "KnightOfShackles": "Der Ritter des Schreckens legt der Feste Ketten an, die fester sitzen als jede Mauer.",
    "MaidenOfThorns": "Die Dornen-Maid lässt ihr Gestrüpp durch die Feste wachsen, bis kein freier Weg mehr bleibt.",
    "GateWitch": "Die Riss-Furie reißt ein Tor mitten durch die Feste — und das, was hindurchtritt, kennt kein Erbarmen.",
    "HollowCrown": "Die Krone der Leere setzt sich über die Feste, und mit ihr verstummt jede Hoffnung.",
    "MagusOfCloaks": "Der Schattenmantel-Magus verhüllt die Feste in Dunkelheit, bevor der letzte Verteidiger sie überhaupt sehen kann.",
    "UmbraTitan": "Der Schatten-Titan durchschreitet die Feste mit einem einzigen, alles verschlingenden Schritt."
  }
};
